Write a function that looks at the first row of a matrix and checks if it doesnt have the number 1, it places the number 1 where there is a 0 or an empty array.

In [1]:
import numpy as np

In [2]:
# Initialise empty sudoku board

board_array = [ [0,0,0, 0,0,0, 0,0,0],
                    [0,0,0, 0,0,0, 0,0,0],
                    [0,0,0, 0,0,0, 0,0,0],

                    [0,0,0, 0,0,0, 0,0,0],
                    [0,0,0, 0,0,0, 0,0,0],
                    [0,0,0, 0,0,0, 0,0,0],

                    [0,0,0, 0,0,0, 0,0,0],
                    [0,0,0, 0,0,0, 0,0,0],
                    [0,0,0, 0,0,0, 0,0,0]
                    ]

print(board_array)
print("\nExamine properties of array above\n")
print("SHAPE:",np.shape(board_array))
print("LENGTH:",len(board_array))
print("TYPE",type(board_array),"\n")


# convert array to matrix using numpy

board_matrix = np.asmatrix(board_array)
print(board_matrix)
print("\nExamine properties of the matrix above\n")
print("SHAPE:",np.shape(board_matrix))
print("LENGTH:",len(board_matrix))
print("TYPE",type(board_matrix),"\n")

[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]]

Examine properties of array above

SHAPE: (9, 9)
LENGTH: 9
TYPE <class 'list'> 

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]

Examine properties of the matrix above

SHAPE: (9, 9)
LENGTH: 9
TYPE <class 'numpy.matrix'> 



In [3]:
# Extract the first row of the list above

board_array_first_row = board_array[0]

print(board_array_first_row)

[0, 0, 0, 0, 0, 0, 0, 0, 0]


In [4]:
# Replace the first row with numbers 2 to 9

for i in range(len(board_array[0])-1):
    board_array[0][i+1]=i+2
    
print(board_array)
print(board_array[0])

[[0, 2, 3, 4, 5, 6, 7, 8, 9], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]]
[0, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
# If 1 is not in the first row, then replace every 0 or empty array with 1

if 1 not in board_array:
    if board_array[0][0] == 0 or isinstance(board_array,np.ndarray):
        if board_array[0][0] != 1:
            board_array[0][0] = [1]
            
print(board_array,"\n")
print(board_array_first_row)

[[[1], 2, 3, 4, 5, 6, 7, 8, 9], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]] 

[[1], 2, 3, 4, 5, 6, 7, 8, 9]


Solve a simple sudoku puzzle!

In [6]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

In [7]:
print(board_array[5])

[4, 9, 6, 3, 0, 8, 1, 7, 2]


In [8]:
isinstance(board_array, list)

True

In [9]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

if 5 not in board_array[5]:
    if board_array[5][4] == 0:
        if board_array[5][4] != 5:
            board_array[5][4] = []
            board_array[5][4].append(5)
    elif isinstance(board_array[5][4],list) and 5 not in board_array[5][4]:
        board_array[5][4].append(5)

        
#print(np.matrix(board_array),"\n")
print(board_array[5])

[4, 9, 6, 3, [5], 8, 1, 7, 2]


Create a function that takes in a list - the sudoku board array, and outputs another list - the sudoku board array but with all the possibilities in the empty spaces.

Q - What does the function do?
It takes in row by row and checks if the numbers from 1 to 9 are in the row, and if they are not, adds them to the empty spaces.

In [10]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(1,10):
        if i not in board_array[j-1]:
            for k in range(1,10):
                if board_array[j-1][k-1] == 0:
                    if board_array[j-1][k-1] != i:
                        board_array[j-1][k-1] = []
                        board_array[j-1][k-1].append(i)
                elif isinstance(board_array[j-1][k-1],list) and i not in board_array[j-1][k-1]:
                    board_array[j-1][k-1].append(i)
                    
print(board_array,"\n")
#print(np.array(board_array))

[[5, [1, 2, 8], [1, 2, 8], 4, 6, 7, 3, [1, 2, 8], 9], [9, [5, 6], 3, 8, 1, [5, 6], 4, 2, 7], [1, 7, 4, 2, [5, 6, 8, 9], 3, [5, 6, 8, 9], [5, 6, 8, 9], [5, 6, 8, 9]], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, [3, 6], 9, [3, 6]], [4, 9, 6, 3, [5], 8, 1, 7, 2], [[1, 3, 4, 5, 7], [1, 3, 4, 5, 7], [1, 3, 4, 5, 7], [1, 3, 4, 5, 7], 8, 9, 2, 6, [1, 3, 4, 5, 7]], [7, 8, 2, 6, 4, 1, [3, 9], [3, 9], 5], [[2, 3, 4, 5, 6, 9], 1, [2, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], 7, [2, 3, 4, 5, 6, 9], 8]] 



In [11]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

print(np.array(board_array)[:,0])

if 3 not in np.array(board_array)[:,0]:
    if board_array[6][0] == 0:
        board_array[6][0] = []
        board_array[6][0].append(3)
    elif isinstance(board_array[6][0],list) and 3 not in board_array[6][0]:
        board_array[6][0].append(3)

print(board_array)

# if 5 not in board_array[5]:
#     if board_array[5][4] == 0:
#         if board_array[5][4] != 5:
#             board_array[5][4] = []
#             board_array[5][4].append(5)
#     elif isinstance(board_array[5][4],list) and 5 not in board_array[5][4]:
#         board_array[5][4].append(5)

# for i in range(1,10):
#     for j in range(1,10):
#         if i not in board_array[j-1]:
#             for k in range(1,10):
#                 if board_array[j-1][k-1] == 0:
#                     if board_array[j-1][k-1] != i:
#                         board_array[j-1][k-1] = []
#                         board_array[j-1][k-1].append(i)
#                 elif isinstance(board_array[j-1][k-1],list):
#                     board_array[j-1][k-1].append(i)

[5 9 1 2 8 4 0 7 0]
[[5, 0, 0, 4, 6, 7, 3, 0, 9], [9, 0, 3, 8, 1, 0, 4, 2, 7], [1, 7, 4, 2, 0, 3, 0, 0, 0], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 0, 9, 0], [4, 9, 6, 3, 0, 8, 1, 7, 2], [[3], 0, 0, 0, 8, 9, 2, 6, 0], [7, 8, 2, 6, 4, 1, 0, 0, 5], [0, 1, 0, 0, 0, 0, 7, 0, 8]]


NEXT: Add statements row and column ifs together before adding a number to the list of possibilities.
An example of the logic is this: if the number 3 does not appear in the row, AND the number 3 does not appear in the column, then append in to the list.

In [12]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

if 2 not in board_array[0] and 2 not in np.array(board_array)[:,7]:
    if board_array[0][7] == 0:
        board_array[0][7] = []
        board_array[0][7].append(2)
    elif isinstance(board_array[0][7],list) and 2 not in board_array[0][7]:
        board_array[0][7].append(2)

print(np.array(board_array))

#it works! - if you like contrast this without adding the AND statement by uncommenting the following piece of code:
# if 2 not in board_array[0] :#(and 2 not in np.array(board_array)[:,7]:)
#     if board_array[0][7] == 0:
#         board_array[0][7] = []
#         board_array[0][7].append(2)
#     elif isinstance(board_array[0][7],list) and 2 not in board_array[0][7]:
#         board_array[0][7].append(2)

[[5 0 0 4 6 7 3 0 9]
 [9 0 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 8]]


Now onto the next challenge - create an if statement to add a number to the list of possibilities, if the number is not contained in the 3x3 box.

In [13]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

print(np.array(board_array)[0:3,0:3])

[[5 0 0]
 [9 0 3]
 [1 7 4]]


In [14]:
5 in np.array(board_array)[0:3,0:3]

True

In [15]:
2 in np.array(board_array)[0:3,0:3]

False

In [16]:
print(np.array(board_array)[0:3,6:9])

[[3 0 9]
 [4 2 7]
 [0 0 0]]


In [17]:
1 not in np.array(board_array)[0:3,6:9]

True

In [18]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

print("before:",board_array[0][7])

if 1 not in np.array(board_array)[0:3,6:9]:
    if board_array[0][7] == 0:
        board_array[0][7] = []
        board_array[0][7].append(1)
    elif isinstance(board_array[0][7],list) and 1 not in board_array[0][7]:
        board_array[0][7].append(1)

print("\nafter",board_array[0][7])
#print(np.array(board_array))

before: 0

after [1]


now the challenge - figuring out how to design a loop that looks through all 9 3x3 squares and fills in all the possibilities

In [29]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# list all the squares:

print("\n1",np.array(board_array)[0:3,0:3])
print("\n2",np.array(board_array)[0:3,3:6])
print("\n3",np.array(board_array)[0:3,6:9])
print("\n4",np.array(board_array)[3:6,0:3])
print("\n5",np.array(board_array)[3:6,3:6])
print("\n6",np.array(board_array)[3:6,6:9])
print("\n7",np.array(board_array)[6:9,0:3])
print("\n8",np.array(board_array)[6:9,3:6])
print("\n9",np.array(board_array)[6:9,6:9])


1 [[5 0 0]
 [9 0 3]
 [1 7 4]]

2 [[4 6 7]
 [8 1 0]
 [2 0 3]]

3 [[3 0 9]
 [4 2 7]
 [0 0 0]]

4 [[2 3 1]
 [8 5 7]
 [4 9 6]]

5 [[9 7 6]
 [1 2 4]
 [3 0 8]]

6 [[8 5 4]
 [0 9 0]
 [1 7 2]]

7 [[0 0 0]
 [7 8 2]
 [0 1 0]]

8 [[0 8 9]
 [6 4 1]
 [0 0 0]]

9 [[2 6 0]
 [0 0 5]
 [7 0 8]]


In [37]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in [0,3,6]:
    for j in [0,3,6]:
            print("\n", np.array(board_array)[i:i+3,j:j+3])


 [[5 0 0]
 [9 0 3]
 [1 7 4]]

 [[4 6 7]
 [8 1 0]
 [2 0 3]]

 [[3 0 9]
 [4 2 7]
 [0 0 0]]

 [[2 3 1]
 [8 5 7]
 [4 9 6]]

 [[9 7 6]
 [1 2 4]
 [3 0 8]]

 [[8 5 4]
 [0 9 0]
 [1 7 2]]

 [[0 0 0]
 [7 8 2]
 [0 1 0]]

 [[0 8 9]
 [6 4 1]
 [0 0 0]]

 [[2 6 0]
 [0 0 5]
 [7 0 8]]


Figure out the logic in words for how the squares:

If 1 is not in the first place (i.e. list place [0][0]), then check if 1 exists in the first 3x3 box [0:3][0:3], and if not, place 1 in the [0][0] position.

Question: How do we get the box range without hard coding it?

Answer: From the position of the number

For example:
if row is in range 0-2 and column is 0-2, then box is [0:3][0:3].
if row is in range 6-8 and column is 3-5, then box is [6:9][3:6].

In [22]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

print("before:",board_array[0][7])

if 1 not in np.array(board_array)[0:3,6:9]:
    if board_array[0][7] == 0:
        board_array[0][7] = []
        board_array[0][7].append(1)
    elif isinstance(board_array[0][7],list) and 1 not in board_array[0][7]:
        board_array[0][7].append(1)

print("\nafter",board_array[0][7])
print("\n",np.array(board_array))

before: 0

after [1]

 [[5 0 0 4 6 7 3 list([1]) 9]
 [9 0 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\1993714519.py:24: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n",np.array(board_array))


In [23]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]


#number
for i in range(1,10):
    #row
    for j in range(3):
        #column
        for k in range(3):
            if i not in np.array(board_array)[0:3,0:3]:
                if board_array[j][k] == 0:
                    if board_array[j][k] != i:
                        board_array[j][k] = []
                        board_array[j][k].append(i)
                elif isinstance(board_array[j][k],list) and i not in board_array[j][k]:
                    board_array[j][k].append(i)
                    
#print(board_array,"\n")
print(np.array(board_array))

[[5 list([2, 6, 8]) list([2, 6, 8]) 4 6 7 3 0 9]
 [9 list([2, 6, 8]) 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\110351542.py:21: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[0:3,0:3]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\110351542.py:30: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(board_array))


In [27]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]


#number
for i in range(1,10):
    #row
    for j in range(9):
        #column
        for k in range(9):
            for m in range(9):
                for n in range(9):
                    #if m <= 3 and n <=3 and j <=3 and k <= 3:
                    if all(p <= 3 for p in [j,k,m,n]):
                        if i not in np.array(board_array)[0:3,0:3]:
                            if board_array[j][k] == 0:
                                if board_array[j][k] != i:
                                    board_array[j][k] = []
                                    board_array[j][k].append(i)
                            elif isinstance(board_array[j][k],list) and i not in board_array[j][k]:
                                board_array[j][k].append(i)
#                     if m <= 3 and n <=3:
#                         if i not in np.array(board_array)[0:3,0:3]:
#                             if board_array[j][k] == 0:
#                                 if board_array[j][k] != i:
#                                     board_array[j][k] = []
#                                     board_array[j][k].append(i)
#                             elif isinstance(board_array[j][k],list) and i not in board_array[j][k]:
#                                 board_array[j][k].append(i)
                                
                             
#print(board_array,"\n")
print(np.array(board_array))

[[5 list([2, 6, 8]) list([2, 6, 8]) 4 6 7 3 0 9]
 [9 list([2, 6, 8]) 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\202945296.py:25: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[0:3,0:3]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\202945296.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(board_array))


In [41]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]


#number
for i in range(2):
    #row
    for j in range(9):
        #column
        for k in range(9):
            for m in [0,3,6]:
                for n in [0,3,6]:
                    if i not in np.array(board_array)[m:m+3,n:n+3]:
                        if board_array[j][k] == 0:
                            if board_array[j][k] != i:
                                board_array[j][k] = []
                                board_array[j][k].append(i)
                                print(np.array(board_array))
                        elif isinstance(board_array[j][k],list) and i not in board_array[j][k]:
                            board_array[j][k].append(i)
                    
#print(board_array,"\n")
print(np.array(board_array))

C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\248257696.py:24: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(board_array))
C:\Users\Daniel\AppData\Local\Temp\ipykernel_10908\248257696.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[m:m+3,n:n+3]:


[[5 0 0 4 6 7 3 0 9]
 [9 0 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 list([2])]]
[[5 0 0 4 6 7 3 0 9]
 [9 0 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 list([3])]]
[[5 0 0 4 6 7 3 0 9]
 [9 0 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 list([3])]]


IndexError: list index out of range