Build recursive sudoku function

In [2]:
import numpy as np

In [4]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# 1. FIRST STAGE - ADD ALL POSSIBILITIES
# add lists of possibilities in each empty box from looking at rows and columns (to add squares in the future)
for i in range(1,10):
    for j in range(9):
        for k in range(9):
            if i not in board_array[j] and i not in np.array(board_array)[:,k]:
                    if board_array[j][k] == 0:
                        if board_array[j][k] != i:
                            board_array[j][k] = []
                            board_array[j][k].append(i)
                    elif isinstance(board_array[j][k],list) and i not in board_array[j][k]:
                        board_array[j][k].append(i)
                    
print("\n"*2, "Both rules together:\n", np.array(board_array))

# 2. SECOND STAGE - FILL IN NUMBERS IF 1 POSSIBILITY ONLY, THEN LOOK AT THE BOARD AND REMOVE POSSIBILITIES, THEN REPEAT

# fill in the box with the number if there is only 1 possibility in the box

for i in range(1,10):
    for j in range(9):
        for k in range(9):
            if isinstance(board_array[j][k], list) and len(board_array[j][k]) == 1:
                board_array[j][k] = board_array[j][k][0]
                
print("\n"*2, np.array(board_array))

# remove any possibilities in the box that are no longer accurate by looking at rows and columns (to add squares in the future)

for i in range(1,10):
    for j in range(9):
        for k in range(9):
            if i in board_array[j] or i in np.array(board_array)[:,k]:
                if isinstance(board_array[j][k],list) and i in board_array[j][k]:
                    board_array[j][k].remove(i)
                    
print("\n"*2, np.array(board_array))



 Both rules together:
 [[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [l

C:\Users\Daniel\AppData\Local\Temp\ipykernel_6072\3465284787.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in board_array[j] and i not in np.array(board_array)[:,k]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_6072\3465284787.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, "Both rules together:\n", np.array(board_array))
C:\Users\Daniel\AppData\Local\Temp\ipykernel_6072\3465284787.py:39: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarr

In [5]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if isinstance(board_array[j-1][k-1], list) and len(board_array[j-1][k-1]) == 1:
                board_array[j-1][k-1] = board_array[j-1][k-1][0]
                
print("\n"*2, np.array(board_array))

# remove any possibilities in the box that are no longer accurate by looking at rows and columns (to add squares in the future)

for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
                if isinstance(board_array[j-1][k-1],list) and i in board_array[j-1][k-1]:
                    board_array[j-1][k-1].remove(i)
                    
print("\n"*2, np.array(board_array))



 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 list([3, 9]) 2 7 4 8]]


 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 list([3]) 2 7 4 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_16136\2080531310.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, np.array(board_array))
C:\Users\Daniel\AppData\Local\Temp\ipykernel_16136\2080531310.py:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_16136\2080531310.py:18: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or

In [6]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if isinstance(board_array[j-1][k-1], list) and len(board_array[j-1][k-1]) == 1:
                board_array[j-1][k-1] = board_array[j-1][k-1][0]
                
print("\n"*2, np.array(board_array))

# remove any possibilities in the box that are no longer accurate by looking at rows and columns (to add squares in the future)

for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
                if isinstance(board_array[j-1][k-1],list) and i in board_array[j-1][k-1]:
                    board_array[j-1][k-1].remove(i)
                    
print("\n"*2, np.array(board_array))



 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]


 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]


Write a function for the above

In [7]:
def add_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i not in board[j] and i not in np.array(board)[:,k]:
                        if board[j][k] == 0:
                            if board[j][k] != i:
                                board[j][k] = []
                                board[j][k].append(i)
                        elif isinstance(board[j][k],list) and i not in board[j][k]:
                            board[j][k].append(i)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board)[:,k]:
                    if isinstance(board[j][k],list) and i in board[j][k]:
                        board[j][k].remove(i)

In [8]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

add_possibilities(board_array)
print(np.array(board_array))

fill_box(board_array)
print("\n"*2,np.array(board_array))

remove_possibilities(board_array)
print("\n"*2,np.array(board_array))

fill_box(board_array)
print("\n"*2,np.array(board_array))

remove_possibilities(board_array)
print("\n"*2,np.array(board_array))

fill_box(board_array)
print("\n"*2,np.array(board_array))

[[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [list([6]) 1 list([9]) 5 li

C:\Users\Daniel\AppData\Local\Temp\ipykernel_6072\1688614018.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in board[j] and i not in np.array(board)[:,k]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_6072\2175975198.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(board_array))
C:\Users\Daniel\AppData\Local\Temp\ipykernel_6072\2175975198.py:18: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprec

In [ ]:
def sudoku_solver(board):
    add_possibilities(board_array)
    print(np.array(board_array))
    
    if 
    fill_box(board_array)
    print("\n"*2,np.array(board_array))

    remove_possibilities(board_array)
    print("\n"*2,np.array(board_array))