### Sudoku solver - version 1
Able to solve beginner level Sudokus that don't even require considering the squares in the board, only rows and columns.


An example of an easy level sudoku is given below. I have linked the website where I got this puzzle from.


An example of an medium level sudoku is also given in the last cell. You will notice that if you run it, the kernel will sooner or later crash. This is because that sudoku is not solvable with this algorithm. For that you will have to use version 2!

In [1]:
# import numpy for numpy.array function when trying to isolate all the columns of the board
import numpy as np

In [2]:
# Helper function used in the add all possibilities function below.
# This is more important in version 2 of the solver when we add the check of all the 3x3 squares.
def add_possibility(board,i,j,k):
    if board[j][k] == 0:
        if board[j][k] != i:
            board[j][k] = []
            board[j][k].append(i)
    elif isinstance(board[j][k],list) and i not in board[j][k]:
        board[j][k].append(i)


def add_all_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                        add_possibility(board,i,j,k)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    if isinstance(board[j][k],list) and i in board[j][k]:
                        board[j][k].remove(i)

In [3]:
def sudoku_solver(board):
    add_all_possibilities(board)
    #print(np.array(board, dtype=object))
    
    fill_box(board)
    #print("\n"*2,np.array(board, dtype=object))

    remove_possibilities(board)
    #print("\n"*2,np.array(board, dtype=object))
    
    # Produce an array with values True or False depending on whether any of the boxes contain a list of possibilities or not
    # If we still have lists, then we've got work to do so we have to run the function again.
    
    x = []

    for i in np.array(board, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))

    # If there are any True values - i.e. lists that have possible numbers in them, then repeat the loop again.
    if any(i for i in x) is True:
        #print("\nBOARD!:",board,"\n")
        sudoku_solver(board)
    # Else if there are no lists left... The puzzle is solved!
    else:
        print("\n"*2,np.array(board, dtype=object))

The board below can be found on [this website](https://www.puzzles-to-print.com/printable-sudokus/sudokus-for-kids/beginner-sudoku-easy.shtml)

For each board you'd like to solve, you'd have to manually input the numbers.

A possible and exciting extension to this project would be to solve the puzzle just by inputting an image of the board. Numbers from the board would be recognised with a simple neural network trained on the [MNIST dataset](https://en.wikipedia.org/wiki/MNIST_database) of handwritten digits. A simple way to "find" the boarders of the board and split it into 81 images, would be to symmetrically split the image in 9x9 equal images. This would assume that the edges of the board are perfectly at the edges of the image.

This would save the fastle of inputting the numbers manually, but in order to work the model needs to have beyond 99% accuracy. Otherwise the solution in the output may be wrong, or the puzzle maybe become unsolvable.

In [4]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# Solve the above board.
# Remember the sudoku_solver function is recursive, meaning that it will call itself unless all the squares have a non-zero or non-list value - i.e. only a single integer
sudoku_solver(board_array)

[[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [list([6]) 1 list([9]) 5 li

In [ ]:
board_array = [ [0,5,0, 0,0,3, 7,0,0],
                [8,3,1, 4,2,7, 0,0,5],
                [9,7,4, 0,8,6, 1,2,3],
               
                [3,8,6, 1,4,0, 2,5,7],
                [7,0,5, 0,0,0, 0,0,0],
                [0,4,9, 7,0,2, 8,3,6],
               
                [5,0,0, 0,7,4, 0,9,8],
                [0,9,0, 3,0,1, 0,0,2],
                [2,0,0, 0,9,0, 3,0,1]
                ]

sudoku_solver(board_array)

In [ ]:
board_array = [ [0,9,0, 0,0,0, 8,3,0],
                [0,0,3, 6,0,0, 0,4,0],
                [0,0,8, 0,0,0, 0,0,0],
                
                [2,0,0, 0,9,0, 0,0,0],
                [0,0,0, 4,3,8, 0,0,0],
                [9,0,5, 0,6,0, 0,0,0],
               
                [0,0,0, 7,0,0, 9,0,0],
                [0,0,0, 0,0,4, 0,0,6],
                [1,7,0, 0,0,0, 0,0,5],
              ]

sudoku_solver(board_array)