### Sudoku solver - version 1
This small algortihm is able to solve beginner level Sudokus that don't even require considering the squares in the board, only the rows and columns.

An example of an easy level sudoku is given below. I have linked the website where I got this puzzle from.

An example of a medium and expert level sudokus are also given in the last cells. You will notice that if you run them, the kernel will sooner or later crash. This is because that puzzle is not solvable with this algorithm. For that we will have to explore later versions (version 3 and beyond) that add a few tricks in our bag.

To understand better what the functions do, I encourage you to go ahead and try and solve some sudokus by yourself. If you can solve hard or expert level sudokus already, you will find these steps way more intuitive. 
Enjoy!

In [1]:
# import numpy for numpy.array function when trying to isolate all the columns of the board
import numpy as np

In [2]:
# Define all the functions we need to solve the puzzle

# If a number does not appear in the row or column that it is in, then append it to a list of possible values
# In theory this function only needs to be ran once to fill in all the possibilities. The other two functions either reduce the possibilities or fill in numbers that are 100% certain
def add_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                    if board[j][k] == 0:
                        if board[j][k] != i:
                            board[j][k] = []
                            board[j][k].append(i)
                    elif isinstance(board[j][k],list) and i not in board[j][k]:
                        board[j][k].append(i)

# Look for any lists that contain only one number. When found, remove the list and only leave the number. This number now becomes a concrete part of the board.
def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]


# Now that the board has slightly changed because of the above function filling in a number that was certain, we need to remove any possibilit 
def remove_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    if isinstance(board[j][k],list) and i in board[j][k]:
                        board[j][k].remove(i)

In [17]:
def sudoku_solver(board):
    # counter variable "n" used to check how many times we need to call the function to solve the puzzle
    # this should be set to zero before running the function and is used to see how many times the function was called before outputting the solved board
    global n
    
    add_possibilities(board)
    #print(np.array(board, dtype=object))
    
    fill_box(board)
    #print("\n"*2,np.array(board, dtype=object))

    remove_possibilities(board)
    #print("\n"*2,np.array(board, dtype=object))
    
    # Produce an array with values True or False depending on whether any of the boxes contain a list of possibilities or not
    # If we still have lists, then we've got work to do so we have to run the function again.
    
    x = []

    for i in np.array(board, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))

    # If there are any True values - i.e. lists that have possible numbers in them, then repeat the loop again.
    if any(i for i in x) is True:
        print("\nThe currect board is:\n",np.array(board, dtype=object))
        # Increase the counter by 1
        n += 1
        sudoku_solver(board)
    # Else if there are no lists left... The puzzle is solved!
    else:
        print("\nSolved in", n+1, "function calls!")
        print("\nThe final board is:\n",np.array(board, dtype=object))

The board below can be found on [this website](https://www.puzzles-to-print.com/printable-sudokus/sudokus-for-kids/beginner-sudoku-easy.shtml)

For each board you'd like to solve, you'd have to manually input the numbers.

A possible and exciting extension to this project would be to solve the puzzle just by inputting an image of the board. Numbers from the board would be recognised with a simple neural network trained on the [MNIST dataset](https://en.wikipedia.org/wiki/MNIST_database) of handwritten digits. A simple way to "find" the boarders of the board and split it into 81 images, would be to symmetrically split the image in 9x9 equal images. This would assume that the edges of the board are perfectly at the edges of the image.

This would save the fastle of inputting the numbers manually, but in order to work the model needs to have beyond 99% accuracy. Otherwise the solution in the output may be wrong, or the puzzle maybe become unsolvable.

In [18]:
# Super easy board
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0

# Solve the above board.
# Remember the sudoku_solver function is recursive, meaning that it will call itself unless all the squares have a non-zero or non-list value - i.e. only a single integer
sudoku_solver(board_array)


The currect board is:
 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [list([6]) 1 list([9]) 5 list([3, 9]) list([2]) 7 list([4]) 8]]

The currect board is:
 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 list([3]) 2 7 4 8]]

Solved in 3 function calls!

The final board is:
 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]


In [20]:
# Medium easy board: https://www.puzzles-to-print.com/printable-sudokus/sudokus-for-kids/beginner-sudoku-medium.shtml
board_array = [ [0,5,0, 0,0,3, 7,0,0],
                [8,3,1, 4,2,7, 0,0,5],
                [9,7,4, 0,8,6, 1,2,3],
               
                [3,8,6, 1,4,0, 2,5,7],
                [7,0,5, 0,0,0, 0,0,0],
                [0,4,9, 7,0,2, 8,3,6],
               
                [5,0,0, 0,7,4, 0,9,8],
                [0,9,0, 3,0,1, 0,0,2],
                [2,0,0, 0,9,0, 3,0,1]
                ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0

# Solve the above board.
# Remember the sudoku_solver function is recursive, meaning that it will call itself unless all the squares have a non-zero or non-list value - i.e. only a single integer
sudoku_solver(board_array)


The currect board is:
 [[list([4, 6]) 5 list([2, 8]) list([2, 6, 8, 9]) list([1, 6]) 3 7
  list([1, 4, 8]) list([4, 9])]
 [8 3 1 4 2 7 list([9]) 6 5]
 [9 7 4 5 8 6 1 2 3]
 [3 8 6 1 4 9 2 5 7]
 [7 list([1, 2]) 5 list([2, 6, 8, 9]) list([1, 3, 6]) list([8])
  list([4, 9]) list([1, 4, 8]) list([4, 9])]
 [1 4 9 7 list([5]) 2 8 3 6]
 [5 list([1, 2]) list([2, 3]) list([2]) 7 4 6 9 8]
 [list([4, 6]) 9 list([7, 8]) 3 list([5, 6]) 1 list([4, 5])
  list([4, 7, 8]) 2]
 [2 6 list([7, 8]) list([8]) 9 list([5, 8]) 3 list([4, 7, 8]) 1]]

The currect board is:
 [[list([4, 6]) 5 list([2, 8]) list([6, 9]) list([1, 6]) 3 7
  list([1, 4, 8]) list([4, 9])]
 [8 3 1 4 2 7 9 6 5]
 [9 7 4 5 8 6 1 2 3]
 [3 8 6 1 4 9 2 5 7]
 [7 list([1, 2]) 5 list([6, 9]) list([1, 3, 6]) 8 list([4]) list([1, 4])
  list([4, 9])]
 [1 4 9 7 5 2 8 3 6]
 [5 list([1]) list([3]) 2 7 4 6 9 8]
 [list([4, 6]) 9 list([7, 8]) 3 list([6]) 1 list([4, 5]) list([4, 7, 8])
  2]
 [2 6 list([7]) 8 9 list([5]) 3 list([4, 7]) 1]]

The currect board

Below is an expert level board taken from: https://suresolv.com/sudoku/solving-sudoku-expert-level-5-game-10-quickly
Our limited algorithm doesn't get close to solving it.

If you dont stop the kernel on the next cell it will run until it crashes as the board is never solved.

In [21]:
# Expert level board
board_array = [ [0,9,0, 0,0,0, 8,3,0],
                [0,0,3, 6,0,0, 0,4,0],
                [0,0,8, 0,0,0, 0,0,0],
                
                [2,0,0, 0,9,0, 0,0,0],
                [0,0,0, 4,3,8, 0,0,0],
                [9,0,5, 0,6,0, 0,0,0],
               
                [0,0,0, 7,0,0, 9,0,0],
                [0,0,0, 0,0,4, 0,0,6],
                [1,7,0, 0,0,0, 0,0,5],
              ]

sudoku_solver(board_array)


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:
 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 6, 7]) 8 3 list([1, 2, 4, 7])]
 [list([5, 7, 8]) list([1, 2, 5, 8]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 8, 9])]
 [list([3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 6, 7, 9])
  list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 5, 6, 7, 9])
  list([1, 2, 3, 4, 7, 9])]
 [2 list([1, 3, 4, 5, 6, 8]) list([1, 4, 6, 7]) list([1, 3, 5, 8]) 9
  list([1, 3, 5, 6, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([5, 6, 7]) list([1, 2, 5, 6]) list([1, 2, 6, 7, 9]) 4 3 8
  list([1, 2, 5, 6, 7]) list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 2, 3, 4, 8]) 5 list([1, 2, 3, 8]) 6 list([1, 2, 3, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([1, 2, 3, 4, 5, 6, 8]) list([1, 2, 4, 6])


The currect board is:


KeyboardInterrupt: 

Maybe we were too ambitious going for expert straight away. Let's try and solve a medium one first.

The below puzzle was taken from here: https://www.rd.com/wp-content/uploads/2020/12/Sudoku-Puzzle_08.pdf
This website also offers 19 other sudoku puzzles at different levels in case you like to test your skills (or the algorithm's skills for that matter): https://www.rd.com/list/printable-sudoku-puzzles/

In [22]:
# Medium sudoku

board_array = [ [1,5,0, 2,0,9, 0,0,4],
                [0,4,0, 0,0,6, 0,0,0],
                [0,0,0, 0,4,0, 0,6,3],
                
                [0,7,0, 0,0,0, 8,0,6],
                [6,0,0, 0,0,0, 0,0,5],
                [2,0,8, 0,0,0, 0,1,0],
               
                [4,6,0, 0,8,0, 0,0,0],
                [0,0,0, 6,0,0, 0,7,0],
                [8,0,0, 5,0,1, 0,4,9],
              ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,


The currect board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 6, 7]) 9 list([3, 6, 7]) list([3, 8]) 4]
 [list([3, 5, 7, 9]) 4 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 8, 9])
  list([1, 2, 3, 5, 7, 9]) 6 list([1, 2, 3, 5, 7, 9])
  list([2, 3, 5, 8, 9]) list([1, 2, 8])]
 [list([5, 7, 9]) list([1, 2, 8, 9]) list([1, 2, 5, 7, 9])
  list([1, 7, 8, 9]) 4 list([2, 5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 2, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 5, 9]) 6]
 [6 list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 7, 9])
  list([1, 3, 4, 7, 8, 9]) list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8])
  list([1, 2, 3, 4, 7, 9]) list([2, 3, 8, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([3, 5, 6, 9]) list([3, 4, 5])
  list([3, 4, 5, 6, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([1, 3, 7, 9]) 8 list([2, 3, 5, 7])
  list([1, 2, 3, 5, 7, 9]) list([2, 3, 5, 9]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 8, 9]) list([1, 2, 3, 4, 5, 9]) 6
  list([1,

KeyboardInterrupt: 

As you can see if you had the courage to run the function on the above board, we still have a lot of work to do.

From a quick skim through the board, I spotted only one list of possibilities having 2 values. The rest had 3, 4, some even 6 possible numbers. 

Go to version 2 to find out how well adding the 3x3 box check does against harder sudokus like the one above!

In [ ]:
+