Sudoku board - file 3

In [4]:
import numpy as np

In [5]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(1,10):
        if i not in board_array[j-1]:
            for k in range(1,10):
                if board_array[j-1][k-1] == 0:
                    if board_array[j-1][k-1] != i:
                        board_array[j-1][k-1] = []
                        board_array[j-1][k-1].append(i)
                elif isinstance(board_array[j-1][k-1],list) and i not in board_array[j-1][k-1]:
                    board_array[j-1][k-1].append(i)
                    
print(board_array,"\n")
#print(np.array(board_array))

[[5, [1, 2, 8], [1, 2, 8], 4, 6, 7, 3, [1, 2, 8], 9], [9, [5, 6], 3, 8, 1, [5, 6], 4, 2, 7], [1, 7, 4, 2, [5, 6, 8, 9], 3, [5, 6, 8, 9], [5, 6, 8, 9], [5, 6, 8, 9]], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, [3, 6], 9, [3, 6]], [4, 9, 6, 3, [5], 8, 1, 7, 2], [[1, 3, 4, 5, 7], [1, 3, 4, 5, 7], [1, 3, 4, 5, 7], [1, 3, 4, 5, 7], 8, 9, 2, 6, [1, 3, 4, 5, 7]], [7, 8, 2, 6, 4, 1, [3, 9], [3, 9], 5], [[2, 3, 4, 5, 6, 9], 1, [2, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], 7, [2, 3, 4, 5, 6, 9], 8]] 



In [8]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

if 2 not in board_array[0] and 2 not in np.array(board_array)[:,7]:
    if board_array[0][7] == 0:
        board_array[0][7] = []
        board_array[0][7].append(2)
    elif isinstance(board_array[0][7],list) and 2 not in board_array[0][7]:
        board_array[0][7].append(2)

print(np.array(board_array))

#it works! - if you like contrast this without adding the AND statement by uncommenting the following piece of code:
# if 2 not in board_array[0] :#(and 2 not in np.array(board_array)[:,7]:)
#     if board_array[0][7] == 0:
#         board_array[0][7] = []
#         board_array[0][7].append(2)
#     elif isinstance(board_array[0][7],list) and 2 not in board_array[0][7]:
#         board_array[0][7].append(2)
# print(np.array(board_array))

[[5 0 0 4 6 7 3 0 9]
 [9 0 3 8 1 0 4 2 7]
 [1 7 4 2 0 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 8]]


In [18]:
# APPLY ROW RULE ONLY:

board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(1,10):
        if i not in board_array[j-1]:
            for k in range(1,10):
                if board_array[j-1][k-1] == 0:
                    if board_array[j-1][k-1] != i:
                        board_array[j-1][k-1] = []
                        board_array[j-1][k-1].append(i)
                elif isinstance(board_array[j-1][k-1],list) and i not in board_array[j-1][k-1]:
                    board_array[j-1][k-1].append(i)
                    
#print(board_array,"\n")
print("\n"*2, "Row rule:\n", np.array(board_array))


# APPLY COLUMN RULE ONLY:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(1,10):
        if i not in np.array(board_array)[:,j-1]:
            for k in range(1,10):
                if board_array[k-1][j-1] == 0:
                    if board_array[k-1][j-1] != i:
                        board_array[k-1][j-1] = []
                        board_array[k-1][j-1].append(i)
                elif isinstance(board_array[k-1][j-1],list) and i not in board_array[k-1][j-1]:
                    board_array[k-1][j-1].append(i)

print("\n"*2, "Column rule:\n", np.array(board_array))

# NOW ADD THE COLUMN RULE ALONG WITH THE ROW RULE TOGETHER:

board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i not in board_array[j-1] and i not in np.array(board_array)[:,k-1]:
                    if board_array[j-1][k-1] == 0:
                        if board_array[j-1][k-1] != i:
                            board_array[j-1][k-1] = []
                            board_array[j-1][k-1].append(i)
                    elif isinstance(board_array[j-1][k-1],list) and i not in board_array[j-1][k-1]:
                        board_array[j-1][k-1].append(i)
                    
#print(board_array,"\n")
print("\n"*2, "Both rules together:\n", np.array(board_array))



 Row rule:
 [[5 list([1, 2, 8]) list([1, 2, 8]) 4 6 7 3 list([1, 2, 8]) 9]
 [9 list([5, 6]) 3 8 1 list([5, 6]) 4 2 7]
 [1 7 4 2 list([5, 6, 8, 9]) 3 list([5, 6, 8, 9]) list([5, 6, 8, 9])
  list([5, 6, 8, 9])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([3, 6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([1, 3, 4, 5, 7]) list([1, 3, 4, 5, 7]) list([1, 3, 4, 5, 7])
  list([1, 3, 4, 5, 7]) 8 9 2 6 list([1, 3, 4, 5, 7])]
 [7 8 2 6 4 1 list([3, 9]) list([3, 9]) 5]
 [list([2, 3, 4, 5, 6, 9]) 1 list([2, 3, 4, 5, 6, 9])
  list([2, 3, 4, 5, 6, 9]) list([2, 3, 4, 5, 6, 9])
  list([2, 3, 4, 5, 6, 9]) 7 list([2, 3, 4, 5, 6, 9]) 8]]


 Column rule:
 [[5 list([2, 4, 6]) list([5, 8, 9]) 4 6 7 3 list([1, 3, 4, 8]) 9]
 [9 list([2, 4, 6]) 3 8 1 list([2, 5]) 4 2 7]
 [1 7 4 2 list([3, 5, 9]) 3 list([5, 6, 9]) list([1, 3, 4, 8])
  list([1, 3, 6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([5, 6, 9]) 9 list([1, 3, 6])]
 [4 9 6 3 list([3, 5, 9]) 8 1 7 2]
 [list([3, 6]) list([2, 4, 6]) list([5, 8, 9]) lis

C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\1621707753.py:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, "Row rule:\n", np.array(board_array))
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\1621707753.py:47: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[:,j-1]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\1621707753.py:56: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shap

In [31]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i not in board_array[j-1] and i not in np.array(board_array)[:,k-1]:
                    if board_array[j-1][k-1] == 0:
                        if board_array[j-1][k-1] != i:
                            board_array[j-1][k-1] = []
                            board_array[j-1][k-1].append(i)
                    elif isinstance(board_array[j-1][k-1], list) and i not in board_array[j-1][k-1]:
                        board_array[j-1][k-1].append(i)
                    
#print(board_array,"\n")
print("\n"*2, "Both row and column rules applied together:\n", np.array(board_array))

for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if isinstance(board_array[j-1][k-1], list) and len(board_array[j-1][k-1]) == 1:
                board_array[j-1][k-1] = board_array[j-1][k-1][0]
                
print("\n"*2, np.array(board_array))



 Both row and column rules applied together:
 [[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\338762454.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in board_array[j-1] and i not in np.array(board_array)[:,k-1]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\338762454.py:26: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, "Both row and column rules applied together:\n", np.array(board_array))
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\338762454.py:34: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple 

In [32]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i not in board_array[j-1] and i not in np.array(board_array)[:,k-1]:
                    if board_array[j-1][k-1] == 0:
                        if board_array[j-1][k-1] != i:
                            board_array[j-1][k-1] = []
                            board_array[j-1][k-1].append(i)
                    elif isinstance(board_array[j-1][k-1],list) and i not in board_array[j-1][k-1]:
                        board_array[j-1][k-1].append(i)
                    
#print(board_array,"\n")
print("\n"*2, np.array(board_array))



 Both rules together:
 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\1508432985.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in board_array[j-1] and i not in np.array(board_array)[:,k-1]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\1508432985.py:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, "Both rules together:\n", np.array(board_array))


NEXT STEP: Remove numbers that can no longer be there after first application of function.

In [33]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
                if isinstance(board_array[j-1][k-1],list) and i in board_array[j-1][k-1]:
                    board_array[j-1][k-1].remove(i)
                    
print("\n"*2, np.array(board_array))



 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [list([6]) 1 list([9]) 5 list([3, 9]) list([2]) 7 list([4]) 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\2497966789.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\2497966789.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, np.array(board_array))


In [37]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if isinstance(board_array[j-1][k-1], list) and len(board_array[j-1][k-1]) == 1:
                board_array[j-1][k-1] = board_array[j-1][k-1][0]
                
print("\n"*2, np.array(board_array))



 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 list([3, 9]) 2 7 4 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\1068944800.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, np.array(board_array))


In [38]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
                if isinstance(board_array[j-1][k-1],list) and i in board_array[j-1][k-1]:
                    board_array[j-1][k-1].remove(i)
                    
print("\n"*2, np.array(board_array))



 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 list([3]) 2 7 4 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\2497966789.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i in board_array[j-1] or i in np.array(board_array)[:,k-1]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_11044\2497966789.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print("\n"*2, np.array(board_array))


In [39]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            if isinstance(board_array[j-1][k-1], list) and len(board_array[j-1][k-1]) == 1:
                board_array[j-1][k-1] = board_array[j-1][k-1][0]
                
print("\n"*2, np.array(board_array))



 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]


# IT WORKED!