### Version 2: With squares

Can solve harder sudokus

In [1]:
import numpy as np

In [2]:
def add_possibility(board, i, j, k):
    if board[j][k] == 0:
        if board[j][k] != i:
            board[j][k] = []
            board[j][k].append(i)
    elif isinstance(board[j][k],list) and i not in board[j][k]:
        board[j][k].append(i)


def add_all_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                    if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                        if j <= 2:
                            if k <= 2:
                                if i not in np.array(board,dtype=object)[0:3, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[0:3, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[0:3, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=5 and j > 2:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[3:6, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[3:6, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[3:6, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=8 and j > 5:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[6:9, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[6:9, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[6:9, 6:9]:
                                    add_possibility(board,i,j,k)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibility(board, i, j, k):
    if isinstance(board[j][k],list) and i in board[j][k]:
        board[j][k].remove(i)

def remove_row_column_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    remove_possibility(board,i,j,k)

def remove_square_possibilities(board):
    for i in range(1,10):
            for j in range(9):
                for k in range(9):
                    if j <= 2:
                        if k <= 2:
                            if i in np.array(board,dtype=object)[0:3, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[0:3, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[0:3, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=5 and j > 2:
                        if k <=2:
                            if i in np.array(board,dtype=object)[3:6, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[3:6, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[3:6, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=8 and j > 5:
                        if k <=2:
                            if i in np.array(board,dtype=object)[6:9, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[6:9, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[6:9, 6:9]:
                                remove_possibility(board,i,j,k)    

In [9]:
def sudoku_solver(board):
    add_all_possibilities(board)
    print(np.array(board, dtype=object))
    
    fill_box(board)
    print("\n"*2,np.array(board, dtype=object))

    remove_row_column_possibilities(board)
    print("\n"*2,np.array(board, dtype=object))
    
    remove_square_possibilities(board)
    print("\n"*2,np.array(board, dtype=object))
    
    x = []

    for i in np.array(board, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))
    if any(i for i in x) is True:
        print("\nBOARD!:",board,"\n")
        print("\nSTART OVER\n")
        sudoku_solver(board)
    else:
        print("\nFINISH!!\n",np.array(board, dtype=object))

In [4]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

sudoku_solver(board_array)

[[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5]) list([2, 5]) 7 list([3, 4])
  8]]


 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [list([6]) 1 list([9]) 5 list([3]) list

In [5]:
board_array = [ [0,5,0, 0,0,3, 7,0,0],
                [8,3,1, 4,2,7, 0,0,5],
                [9,7,4, 0,8,6, 1,2,3],
               
                [3,8,6, 1,4,0, 2,5,7],
                [7,0,5, 0,0,0, 0,0,0],
                [0,4,9, 7,0,2, 8,3,6],
               
                [5,0,0, 0,7,4, 0,9,8],
                [0,9,0, 3,0,1, 0,0,2],
                [2,0,0, 0,9,0, 3,0,1]
                ]

sudoku_solver(board_array)

[[list([6]) 5 list([2]) list([9]) list([1]) 3 7 list([4, 6, 8])
  list([4, 9])]
 [8 3 1 4 2 7 list([6, 9]) list([6]) 5]
 [9 7 4 list([5]) 8 6 1 2 3]
 [3 8 6 1 4 list([9]) 2 5 7]
 [7 list([1, 2]) 5 list([6, 8, 9]) list([3, 6]) list([8, 9]) list([4, 9])
  list([1, 4]) list([4, 9])]
 [list([1]) 4 9 7 list([5]) 2 8 3 6]
 [5 list([1, 6]) list([3]) list([2, 6]) 7 4 list([6]) 9 8]
 [list([4, 6]) 9 list([7, 8]) 3 list([5, 6]) 1 list([4, 5, 6])
  list([4, 6, 7]) 2]
 [2 list([6]) list([7, 8]) list([5, 6, 8]) 9 list([5, 8]) 3
  list([4, 6, 7]) 1]]


 [[6 5 2 9 1 3 7 list([4, 6, 8]) list([4, 9])]
 [8 3 1 4 2 7 list([6, 9]) 6 5]
 [9 7 4 5 8 6 1 2 3]
 [3 8 6 1 4 9 2 5 7]
 [7 list([1, 2]) 5 list([6, 8, 9]) list([3, 6]) list([8, 9]) list([4, 9])
  list([1, 4]) list([4, 9])]
 [1 4 9 7 5 2 8 3 6]
 [5 list([1, 6]) 3 list([2, 6]) 7 4 6 9 8]
 [list([4, 6]) 9 list([7, 8]) 3 list([5, 6]) 1 list([4, 5, 6])
  list([4, 6, 7]) 2]
 [2 6 list([7, 8]) list([5, 6, 8]) 9 list([5, 8]) 3 list([4, 6, 7]) 1]]


 [[6 5 2 

In [10]:
# board_array = [ [0,9,0, 0,0,0, 8,3,0],
#                 [0,0,3, 6,0,0, 0,4,0],
#                 [0,0,8, 0,0,0, 0,0,0],
                
#                 [2,0,0, 0,9,0, 0,0,0],
#                 [0,0,0, 4,3,8, 0,0,0],
#                 [9,0,5, 0,6,0, 0,0,0],
               
#                 [0,0,0, 7,0,0, 9,0,0],
#                 [0,0,0, 0,0,4, 0,0,6],
#                 [1,7,0, 0,0,0, 0,0,5],
#               ]

# sudoku_solver(board_array)

[[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) lis



 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) 



 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) 



 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) 



 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) 

[[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) lis



 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) 

[[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) lis

[[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) lis



 [[list([4, 5, 6, 7]) 9 list([1, 2, 4, 6, 7]) list([1, 2, 5])
  list([1, 2, 4, 5, 7]) list([1, 2, 5, 7]) 8 3 list([1, 2, 7])]
 [list([5, 7]) list([1, 2, 5]) 3 6 list([1, 2, 5, 7, 8])
  list([1, 2, 5, 7, 9]) list([1, 2, 5, 7]) 4 list([1, 2, 7, 9])]
 [list([4, 5, 6, 7]) list([1, 2, 4, 5, 6]) 8 list([1, 2, 3, 5, 9])
  list([1, 2, 4, 5, 7]) list([1, 2, 3, 5, 7, 9]) list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [2 list([1, 3, 4, 6, 8]) list([1, 4, 6, 7]) list([1, 5]) 9
  list([1, 5, 7]) list([1, 3, 4, 5, 6, 7]) list([1, 5, 6, 7, 8])
  list([1, 3, 4, 7, 8])]
 [list([6, 7]) list([1, 6]) list([1, 6, 7]) 4 3 8 list([1, 2, 5, 6, 7])
  list([1, 2, 5, 6, 7, 9]) list([1, 2, 7, 9])]
 [9 list([1, 3, 4, 8]) 5 list([1, 2]) 6 list([1, 2, 7])
  list([1, 2, 3, 4, 7]) list([1, 2, 7, 8]) list([1, 2, 3, 4, 7, 8])]
 [list([3, 4, 5, 6, 8]) list([2, 3, 4, 5, 6, 8]) list([2, 4, 6]) 7
  list([1, 2, 5, 8]) list([1, 2, 3, 5, 6]) 9 list([1, 2, 8])
  list([1, 2, 3, 4, 8])]
 [list([3, 5, 8]) 

KeyboardInterrupt: 

In [11]:
board_array = [ [1,5,0, 2,0,9, 0,0,4],
                [0,4,0, 0,0,6, 0,0,0],
                [0,0,0, 0,4,0, 0,6,3],
                
                [0,7,0, 0,0,0, 8,0,6],
                [6,0,0, 0,0,0, 0,0,5],
                [2,0,8, 0,0,0, 0,1,0],
               
                [4,6,0, 0,8,0, 0,0,0],
                [0,0,0, 6,0,0, 0,7,0],
                [8,0,0, 5,0,1, 0,4,9],
              ]

sudoku_solver(board_array)

[[1 5 list([3, 6, 7]) 2 list([3, 7]) 9 list([7]) list([8]) 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 3, 7, 8])
  list([1, 3, 5, 7]) 6 list([1, 2, 5, 7, 9]) list([2, 5, 8, 9])
  list([1, 2, 7, 8])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 7, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 7, 9]) list([3, 5, 6, 7, 9])
  list([3, 4, 5, 7]) list([3, 4, 7, 9]) 1 list([7])]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6
  list([2, 3, 9]) list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list(



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list(

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list(



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list(

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,


START OVER

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7,



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], [1

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,

[[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]


 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1,



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 



 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 7, 8]) list([1, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) list([5, 6, 9]) list([3, 4, 5])
  list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 list([2, 3, 6]) 4 9]]

BOARD!: [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], 

KeyboardInterrupt: 