Improve 2 things

1. Looping mechanism - no need to call the possibilities function

2. Iterate through the squares

1. Looping

We need to:
- do add all possibilities only once
- make a recursive function that first removes possibilities then fills boxes until no lists are present

In [1]:
# import numpy for numpy.array function when trying to isolate all the columns of the board
import numpy as np

In [15]:
# Helper function used in the add all possibilities function below.
# This is added in version 2 of the solver to aid with checking through each square
def add_possibility(board, i, j, k):
    if board[j][k] == 0:
        if board[j][k] != i:
            board[j][k] = []
            board[j][k].append(i)
    elif isinstance(board[j][k],list) and i not in board[j][k]:
        board[j][k].append(i)

# Iterate over each square. This can be tidied up to loop through all the 3x3 squares instead of hardcoding it for each one.
def add_all_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                    if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                        if j <= 2:
                            if k <= 2:
                                if i not in np.array(board,dtype=object)[0:3, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[0:3, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[0:3, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=5 and j > 2:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[3:6, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[3:6, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[3:6, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=8 and j > 5:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[6:9, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[6:9, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[6:9, 6:9]:
                                    add_possibility(board,i,j,k)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibility(board, i, j, k):
    if isinstance(board[j][k],list) and i in board[j][k]:
        board[j][k].remove(i)

def remove_row_column_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    remove_possibility(board,i,j,k)

def remove_square_possibilities(board):
    for i in range(1,10):
            for j in range(9):
                for k in range(9):
                    if j <= 2:
                        if k <= 2:
                            if i in np.array(board,dtype=object)[0:3, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[0:3, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[0:3, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=5 and j > 2:
                        if k <=2:
                            if i in np.array(board,dtype=object)[3:6, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[3:6, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[3:6, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=8 and j > 5:
                        if k <=2:
                            if i in np.array(board,dtype=object)[6:9, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[6:9, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[6:9, 6:9]:
                                remove_possibility(board,i,j,k)  
                                
def recursive_solve(board,n):
    remove_row_column_possibilities(board)
    remove_square_possibilities(board)
    fill_box(board)
    
    print("\nThe currect board is:\n",np.array(board, dtype=object))
    
    # Produce an array with values True or False depending on whether any of the boxes contain a list of possibilities or not
    # If we still have lists, then we've got work to do so we have to run the function again.
    x = []
    
    for i in np.array(board, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))

    # If there are any True values - i.e. lists that have possible numbers in them, then repeat the loop again.
    if any(i for i in x) is True:
        print("\nThe currect board is:\n",np.array(board, dtype=object))
        # Increase the counter by 1
        n += 1
        sudoku_solver(board)
    # Else if there are no lists left... The puzzle is solved!
    else:
        print("\nSolved in", n+1, "function calls!")
        print("\nThe final board is:\n",np.array(board, dtype=object))

In [16]:
def sudoku_solver(board):
    # counter variable "n" used to check how many times we need to call the function to solve the puzzle
    add_all_possibilities(board)
    #print(np.array(board, dtype=object))
    
    fill_box(board)
    #print("\n"*2,np.array(board, dtype=object))

    n = 0

    recursive_solve(board,n)

In [17]:
# Super easy board
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

sudoku_solver(board_array)


The currect board is:
 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]

Solved in 1 function calls!

The final board is:
 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]


2. Iterate through squares to tidy code - im thinking adding 3 each time while the variable is less than 9

this may have to wait because the problem is harder than I thought.
let me focus now on a third more important taks:


3. If you look at a row, column or square and you find that in all the lists a number is listed only once -> bingo! - then fill the box with that number.

In [34]:
# Here is an example board to work with when a row can take advatage of this rule.

board1 = [[5, 2, 8, 4, 6, 7, 3, [1, 8], 9], [9, 6, 3, 8, 1, 5, 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 6, 9, [3, 6]], [4, 9, 6, 3, 5, 8, 1, 7, 2], [3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]], [7, 8, 2, 6, 4, 1, 9, 3, 5], [[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]]

for i in board1:
    print(i)

[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]


In [70]:
board1 = [[5, 2, 8, 4, 6, 7, 3, [1, 8], 9], [9, 6, 3, 8, 1, 5, 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 6, 9, [3, 6]], [4, 9, 6, 3, 5, 8, 1, 7, 2], [3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]], [7, 8, 2, 6, 4, 1, 9, 3, 5], [[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]]

for i in board1:
    print(i)

counter3 = 0
counter6 = 0

for i in range(9):
    if isinstance(board1[8][i], list):
        #print("\nboard row",i+1,"\n",board1[8][i])
        #print(board1[8][i].count(3))
        
        counter3 += board1[8][i].count(3)
        #print("counter3:",counter3)
        
        counter6 += board1[8][i].count(6)
        #print("counter6:",counter6,"\n")

print("Second loop")

if counter6 == 1:
    counter6 = 0
    if isinstance(board1[8][0], list):
        #print("\nboard row",1,"\n",board1[8][0])
        counter6 += board1[8][0].count(6)
        #print("counter6:",counter6,"\n")
    if counter6 == 1:
        board1[8][0] = 6
        #print("\nboard row",1,"\n",board1[8][0])

for i in board1:
    print(i)

[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]
Second loop
[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[6, 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]


In [54]:
board1 = [[5, 2, 8, 4, 6, 7, 3, [1, 8], 9], [9, 6, 3, 8, 1, 5, 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 6, 9, [3, 6]], [4, 9, 6, 3, 5, 8, 1, 7, 2], [3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]], [7, 8, 2, 6, 4, 1, 9, 3, 5], [[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]]

for i in board1:
    print(i)
    
board1[8][0] = 6
print("\n")

for i in board1:
    print(i)

[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]


[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[6, 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]


In [75]:
board1 = [[5, 2, 8, 4, 6, 7, 3, [1, 8], 9], [9, 6, 3, 8, 1, 5, 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 6, 9, [3, 6]], [4, 9, 6, 3, 5, 8, 1, 7, 2], [3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]], [7, 8, 2, 6, 4, 1, 9, 3, 5], [[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]]

for i in board1:
    print(i)

zero_counter = [0,0,0,0,0,0,0,0,0]
counter3 = 0
counter6 = 0

for i in range(9):
    if isinstance(board1[8][i], list):
        #print("\nboard row",i+1,"\n",board1[8][i])
        #print(board1[8][i].count(3))
        
        for j in range(9):
            zero_counter[j] += board1[8][i].count(j+1)
            
            counter3 += board1[8][i].count(3)
            #print("counter3:",counter3)

            counter6 += board1[8][i].count(6)
            #print("counter6:",counter6,"\n")
print("\n",zero_counter)

print("\nSecond loop\n")


for j in range(9):
    if zero_counter[j] == 1:
        zero_counter[j] = 0
        for i in range(9):
            if isinstance(board1[8][i], list):
                zero_counter[j] += board1[8][i].count(j+1)
                print("\ncounter for number", j+1,"is", zero_counter[j])
                #print("\nThe value of row 9, column",j+1,"is",board1[8][i])
            if zero_counter[j] == 1:
                board1[8][i] = j+1
                print("\nThe new value of row 9, column",j+1, "is",board1[8][i])
                break

#break

# if counter6 == 1:
#     counter6 = 0
#     if isinstance(board1[8][0], list):
#         #print("\nboard row",1,"\n",board1[8][0])
#         counter6 += board1[8][0].count(6)
#         #print("counter6:",counter6,"\n")
#     if counter6 == 1:
#         board1[8][0] = 6
#         #print("\nboard row",1,"\n",board1[8][0])

for i in board1:
    print(i)

[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]

 [0, 1, 3, 1, 3, 1, 0, 0, 2]

Second loop


counter for number 2 is 0

counter for number 2 is 0

counter for number 2 is 0

counter for number 2 is 1

The new value of row 9, column 2 is 2

counter for number 4 is 0

counter for number 4 is 0

counter for number 4 is 0

counter for number 4 is 1

The new value of row 9, column 4 is 4

counter for number 6 is 1

The new value of row 9, column 6 is 6
[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[6, 1, [5, 9], 5, [3, 5, 9

In [76]:
zero_counter = [0,0,0,0,0,0,0,0,0]
counter3 = 0
counter6 = 0

for i in range(9):
    if isinstance(board1[8][i], list):
        #print("\nboard row",i+1,"\n",board1[8][i])
        #print(board1[8][i].count(3))
        
        for j in range(9):
            zero_counter[j] += board1[8][i].count(j+1)
            
            counter3 += board1[8][i].count(3)
            #print("counter3:",counter3)

            counter6 += board1[8][i].count(6)
            #print("counter6:",counter6,"\n")
print("\n",zero_counter)

print("\nSecond loop\n")


for j in range(9):
    if zero_counter[j] == 1:
        zero_counter[j] = 0
        for i in range(9):
            if isinstance(board1[8][i], list):
                zero_counter[j] += board1[8][i].count(j+1)
                print("\ncounter for number", j+1,"is", zero_counter[j])
                #print("\nThe value of row 9, column",j+1,"is",board1[8][i])
            if zero_counter[j] == 1:
                board1[8][i] = j+1
                print("\nThe new value of row 9, column",j+1, "is",board1[8][i])
                break

#break

# if counter6 == 1:
#     counter6 = 0
#     if isinstance(board1[8][0], list):
#         #print("\nboard row",1,"\n",board1[8][0])
#         counter6 += board1[8][0].count(6)
#         #print("counter6:",counter6,"\n")
#     if counter6 == 1:
#         board1[8][0] = 6
#         #print("\nboard row",1,"\n",board1[8][0])

for i in board1:
    print(i)


 [0, 0, 1, 0, 2, 0, 0, 0, 2]

Second loop


counter for number 3 is 0

counter for number 3 is 1

The new value of row 9, column 3 is 3
[5, 2, 8, 4, 6, 7, 3, [1, 8], 9]
[9, 6, 3, 8, 1, 5, 4, 2, 7]
[1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6]
[2, 3, 1, 9, 7, 6, 8, 5, 4]
[8, 5, 7, 1, 2, 4, 6, 9, [3, 6]]
[4, 9, 6, 3, 5, 8, 1, 7, 2]
[3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]]
[7, 8, 2, 6, 4, 1, 9, 3, 5]
[6, 1, [5, 9], 5, 3, 2, 7, 4, 8]


It works!

In [83]:
# Function

def single_row_number(board):
    for k in range(9):
        zero_counter = [0,0,0,0,0,0,0,0,0]

        for i in range(9):
            if isinstance(board[k][i], list):
                for j in range(9):
                    zero_counter[j] += board[k][i].count(j+1)
        print("\n",zero_counter)

        print("\nSecond loop\n")

        for j in range(9):
            if zero_counter[j] == 1:
                zero_counter[j] = 0
                for i in range(9):
                    if isinstance(board[k][i], list):
                        zero_counter[j] += board[k][i].count(j+1)
                        print("\ncounter for number", j+1,"is", zero_counter[j])
                    if zero_counter[j] == 1:
                        board[k][i] = j+1
                        print("\nThe new value of row 9, column",j+1, "is",board[k][i])
                        break
    for i in board:
        print(i)

In [84]:
board1 = [[5, 2, 8, 4, 6, 7, 3, [1, 8], 9], [9, 6, 3, 8, 1, 5, 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 6, 9, [3, 6]], [4, 9, 6, 3, 5, 8, 1, 7, 2], [3, 4, 5, [5, 7], 8, 9, 2, 6, [1, 3]], [7, 8, 2, 6, 4, 1, 9, 3, 5], [[3, 6], 1, [5, 9], 5, [3, 5, 9], [2, 5], 7, [3, 4], 8]]

single_row_number(board1)


 [1, 0, 0, 0, 0, 0, 0, 1, 0]

Second loop


counter for number 1 is 1

The new value of row 9, column 1 is 1

 [0, 0, 0, 0, 0, 0, 0, 0, 0]

Second loop


 [0, 0, 0, 0, 2, 1, 0, 0, 2]

Second loop


counter for number 6 is 0

counter for number 6 is 1

The new value of row 9, column 6 is 6

 [0, 0, 0, 0, 0, 0, 0, 0, 0]

Second loop


 [0, 0, 1, 0, 0, 1, 0, 0, 0]

Second loop


counter for number 3 is 1

The new value of row 9, column 3 is 3

 [0, 0, 0, 0, 0, 0, 0, 0, 0]

Second loop


 [1, 0, 1, 0, 1, 0, 1, 0, 0]

Second loop


counter for number 1 is 0

counter for number 1 is 1

The new value of row 9, column 1 is 1

counter for number 3 is 0

counter for number 5 is 1

The new value of row 9, column 5 is 5

 [0, 0, 0, 0, 0, 0, 0, 0, 0]

Second loop


 [0, 1, 3, 1, 3, 1, 0, 0, 2]

Second loop


counter for number 2 is 0

counter for number 2 is 0

counter for number 2 is 0

counter for number 2 is 1

The new value of row 9, column 2 is 2

counter for number 4 is 0

counter for number

In [26]:
# Here is an example board to work with when a column can take advantage of this rule.
# Notice that the last column has only one number 8 so we can fill it in.

board2 =  [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]], [[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 9], 6, 3], [[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6], [6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 9], [2, 3, 9], 5], [2, [3, 9], 8, [3, 4, 9], [5, 6, 9], [3, 4, 5], [3, 4, 9], 1, 7], [4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]], [[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 9], [2, 3, 4], [1, 2, 3, 5], 7, [1, 2, 8]], [8, [2, 3], [2, 3, 7], 5, [2, 7], 1, [2, 3, 6], 4, 9]] 

print(np.array(board2, dtype=object)[:,8],"\n")

[4 list([1, 2]) 3 6 5 7 list([1, 2]) list([1, 2, 8]) 9] 



In [91]:
def single_column_number(board):
    zero_counter = [0,0,0,0,0,0,0,0,0]

    for i in range(9):
        if isinstance(board[i][8], list):
            for j in range(9):
                zero_counter[j] += board[i][8].count(j+1)
    print("\n",zero_counter)

    print("\nSecond loop\n")

    for j in range(9):
        if zero_counter[j] == 1:
            zero_counter[j] = 0
            for i in range(9):
                if isinstance(board[i][8], list):
                    zero_counter[j] += board[i][8].count(j+1)
                    print("\ncounter for number", j+1,"is", zero_counter[j])
                if zero_counter[j] == 1:
                    board[i][8] = j+1
                    print("\nThe new value of row 9, column",j+1, "is",board[i][8])
                    break
    for i in board:
        print(i)

In [92]:
board2 =  [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]], [[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 9], 6, 3], [[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6], [6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 9], [2, 3, 9], 5], [2, [3, 9], 8, [3, 4, 9], [5, 6, 9], [3, 4, 5], [3, 4, 9], 1, 7], [4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]], [[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 9], [2, 3, 4], [1, 2, 3, 5], 7, [1, 2, 8]], [8, [2, 3], [2, 3, 7], 5, [2, 7], 1, [2, 3, 6], 4, 9]] 

for i in board2:
    print(i)

single_column_number(board2)

[1, 5, 6, 2, 3, 9, 7, 8, 4]
[[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]]
[[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 9], 6, 3]
[[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6]
[6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 9], [2, 3, 9], 5]
[2, [3, 9], 8, [3, 4, 9], [5, 6, 9], [3, 4, 5], [3, 4, 9], 1, 7]
[4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]]
[[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 9], [2, 3, 4], [1, 2, 3, 5], 7, [1, 2, 8]]
[8, [2, 3], [2, 3, 7], 5, [2, 7], 1, [2, 3, 6], 4, 9]

 [3, 3, 0, 0, 0, 0, 0, 1, 0]

Second loop


counter for number 8 is 0

counter for number 8 is 0

counter for number 8 is 1

The new value of row 9, column 8 is 8
[1, 5, 6, 2, 3, 9, 7, 8, 4]
[[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]]
[[7, 9], [2, 8, 9], [2, 7, 9], [1,

In [93]:
def single_column_number(board):
    for k in range(9):
        zero_counter = [0,0,0,0,0,0,0,0,0]

        for i in range(9):
            if isinstance(board[i][k], list):
                for j in range(9):
                    zero_counter[j] += board[i][k].count(j+1)
        print("\n",zero_counter)

        print("\nSecond loop\n")

        for j in range(9):
            if zero_counter[j] == 1:
                zero_counter[j] = 0
                for i in range(9):
                    if isinstance(board[i][k], list):
                        zero_counter[j] += board[i][k].count(j+1)
                        print("\ncounter for number", j+1,"is", zero_counter[j])
                    if zero_counter[j] == 1:
                        board[i][k] = j+1
                        print("\nThe new value of row 9, column",j+1, "is",board[i][k])
                        break
        for i in board:
            print(i)
            

board2 =  [[1, 5, 6, 2, 3, 9, 7, 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]], [[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 9], 6, 3], [[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6], [6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 9], [2, 3, 9], 5], [2, [3, 9], 8, [3, 4, 9], [5, 6, 9], [3, 4, 5], [3, 4, 9], 1, 7], [4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]], [[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 9], [2, 3, 4], [1, 2, 3, 5], 7, [1, 2, 8]], [8, [2, 3], [2, 3, 7], 5, [2, 7], 1, [2, 3, 6], 4, 9]] 

for i in board2:
    print(i)

single_column_number(board2)

[1, 5, 6, 2, 3, 9, 7, 8, 4]
[[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]]
[[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 9], 6, 3]
[[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6]
[6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 9], [2, 3, 9], 5]
[2, [3, 9], 8, [3, 4, 9], [5, 6, 9], [3, 4, 5], [3, 4, 9], 1, 7]
[4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]]
[[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 9], [2, 3, 4], [1, 2, 3, 5], 7, [1, 2, 8]]
[8, [2, 3], [2, 3, 7], 5, [2, 7], 1, [2, 3, 6], 4, 9]

 [0, 0, 3, 0, 2, 0, 2, 0, 4]

Second loop

[1, 5, 6, 2, 3, 9, 7, 8, 4]
[[3, 7, 9], 4, [2, 3, 7, 9], [1, 7, 8], [1, 5, 7], 6, [1, 2, 5, 9], [2, 5, 9], [1, 2]]
[[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 9], 6, 3]
[[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 5, 9], [2, 3, 4, 5], 8, [