# Sudoku solver

## 1. Sudoku board

Create a legit sudoku board from scratch

In [1]:
import numpy as np

In [ ]:
# Sidetrack - below is a function that generates 500 random numbers between 1 and 1 million and then checks their average
# I wanted to see if I would roughly get a mean of half a million and indeed I do
# To see these results even better, I could plot a bar chart with groups of numbers of range 100 (i.e. 1-100,101-200, etc.)
# on the x-axis and their occurance in the arrays generated on the y-axis

import random

array = []

for i in range(500):
    x = random.randint(1,1000000)
    array.append(x)
#     print(x)
#     print(array)

sum_terms = sum(array)
num_terms = len(array)
mean = sum_terms/num_terms
print(int(round(mean,0)))

In [ ]:
# import matplotlib.pyplot as plt
# %matplotlib inline
# plt.style.use('ggplot')

# x_axis = []
# for i in range(1,100):
#     x_axis.append(i*100)
# print(x_axis)
    

# energy = [5, 6, 15, 22, 24, 8]

# x_pos = [i for i, _ in enumerate(x)]

# plt.bar(x_pos, energy, color='green')
# plt.xlabel("Energy Source")
# plt.ylabel("Energy Output (GJ)")
# plt.title("Energy output from various fuel sources")

# plt.xticks(x_pos, x)

# plt.show()

In [ ]:
# back to sudoku board

empty_board= [ [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],

               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],

               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0]
              ]

empty_board_2 = [ [ [[0],[0],[0]],
                    [[0],[0],[0]],
                    [[0],[0],[0]]
                  ],[ [[0],[0],[0]],
                    [[0],[0],[0]],
                    [[0],[0],[0]]
                  ]
                ]

In [ ]:
import numpy as np

# explore different object types - np.matrix
a = np.matrix('1 2; 3 4')
b = np.matrix([[1, 2], [3, 4]])

print(a)
print(b)

In [ ]:
c = np.matrix('[0] [0];[0] [0]')
print(c,"\n")

d = np.matrix([[0, 0], [0, 0]])
print(d)

# f = np.matrix([[[0], [0]], [[0], [0]]])
# print(f)
# does not work; returns "matrix must be 2-dimensional"

In [ ]:
A = np.matrix('[0] [0] [0]; [0] [0] [0]; [0] [0] [0]')
print(A,"\n")

# modify elements of the matrix
A[A<2]=1
print(A,"\n")

M = np.matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(M,"\n")

M[M<1]=1
print(M,"\n")

In [ ]:
# try a different method

A = np.ones(9)*0
print(A)
A = A.astype(int)
print(A)
A = A.reshape(3,3)
print(A)
A[A<2]=0
print(A)

In [2]:
# back to ready empty board

empty_board= [ [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],

               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],

               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0],
               [0,0,0, 0,0,0, 0,0,0]
              ]

print(empty_board)

[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [3]:
# convert array to matrix using numpy

matrix_board = np.asmatrix(empty_board)
print(matrix_board)
print("\nThe shape of the above sudoku board matrix is:",matrix_board.shape)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]

The shape of the above sudoku board matrix is: (9, 9)


First problem to solve - Leave the first number as zero and the rest from the first row going from 2 to 9. Find an algorithm that will place a 1 on the place of the first element (1,1) of the sudoku board matrix.

In [6]:
print(matrix_board[8][0])
print("SHAPE:",np.shape(matrix_board[8][0]))
print("LENGTH:",len(matrix_board))
print("TYPE",type(matrix_board[8][0]),"\n")

row_array = np.array(matrix_board[8][0])
print(np.array(matrix_board[8][0]))
print("SHAPE:",np.shape(row_array))
print("LENGTH:",len(row_array))
print("TYPE",type(row_array),"\n")

print(row_array[0][0],"\n")

print(row_array[0])
print("SHAPE:",np.shape(row_array[0]))
print("LENGTH:",len(row_array[0]))
print("TYPE",type(row_array[0]),"\n")

# probably wont need to use this object
int_array = row_array[0].astype(int)
print(int_array)
print("SHAPE:",np.shape(int_array[0]))
# print("LENGTH:",len(int_array[0])) - not applicable
print("TYPE",type(int_array[0]),"\n")

[[0 0 0 0 0 0 0 0 0]]
SHAPE: (1, 9)
LENGTH: 9
TYPE <class 'numpy.matrix'> 

[[0 0 0 0 0 0 0 0 0]]
SHAPE: (1, 9)
LENGTH: 1
TYPE <class 'numpy.ndarray'> 

0 

[0 0 0 0 0 0 0 0 0]
SHAPE: (9,)
LENGTH: 9
TYPE <class 'numpy.ndarray'> 

[0 0 0 0 0 0 0 0 0]
SHAPE: ()
TYPE <class 'numpy.int32'> 



In [8]:
for i in range(len(row_array[0])-1):
    row_array[0][i+1]=i+2
    
print(row_array)
print(row_array[0])

[[0 2 3 4 5 6 7 8 9]]
[0 2 3 4 5 6 7 8 9]


So far I have been able to do the following:
- Extract the first row of my sudoku matrix
- Leave the first element as zero and add the numbers 2 to 9 until the rest of the row

Next steps:
- Change the first row of the sudoku board matrix to the array you created above
- Create an algorithm that does the following:
    - Creates an empty array in the place of all components that are zero. I.e. if the value is zero, then place an empty array in there.
    - If the elements in the array dont have the number x, where x belongs to 1-9, then place x inside the empty array
    - If the array has only 1 value after the above rule has been applied, then convert the array to an int so that only the number is left.

In [46]:
if 1 not in row_array[0]:
    if row_array[0][0] == 0 or isinstance(row_array[0],np.ndarray):
        if row_array[0][0] != 1:
            row_array[0][0] = 1
            print(row_array)

In [40]:
print(row_array[0][0])

0


In [18]:
1 not in row_array[0]

True

In [42]:
row_array[0][0] == 0  or isinstance(row_array[0],np.ndarray)

True

In [47]:
row_array[0][0] != 1

False

Now I need to put the array back in the matrix

In [56]:
print(matrix_board,"\n")
print(matrix_board[0],"\n")
print(row_array)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]] 

[[0 0 0 0 0 0 0 0 0]] 

[[1 2 3 4 5 6 7 8 9]]


In [58]:
matrix_board[0] = row_array
print(matrix_board)

[[1 2 3 4 5 6 7 8 9]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


success!