Functions

In [1]:
import numpy as np

In [2]:
def add_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                        if board[j][k] == 0:
                            if board[j][k] != i:
                                board[j][k] = []
                                board[j][k].append(i)
                        elif isinstance(board[j][k],list) and i not in board[j][k]:
                            board[j][k].append(i)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    if isinstance(board[j][k],list) and i in board[j][k]:
                        board[j][k].remove(i)

In [3]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

add_possibilities(board_array)
print(np.array(board_array, dtype=object))

fill_box(board_array)
print("\n"*2,np.array(board_array, dtype=object))

remove_possibilities(board_array)
print("\n"*2,np.array(board_array, dtype=object))

fill_box(board_array)
print("\n"*2,np.array(board_array, dtype=object))

remove_possibilities(board_array)
print("\n"*2,np.array(board_array, dtype=object))

fill_box(board_array)
print("\n"*2,np.array(board_array, dtype=object))

[[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1, 8]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3, 6])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 9 3 5]
 [list([3, 6]) 1 list([5, 9]) 5 list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]


 [[5 2 8 4 6 7 3 list([1]) 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 list([9]) 3 list([5]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 list([3])]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 list([7]) 8 9 2 6 list([1])]
 [7 8 2 6 4 1 9 3 5]
 [list([6]) 1 list([9]) 5 li

In [4]:
for i in board_array:
    for j in range(9):
        print(type(i[j]))
        print(isinstance(i[j],list))

<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False
<class 'int'>
False


In [5]:
any(x == 'Erik' for x in ['Erik', 'John', 'Jane', 'Jim'])

True

In [6]:
board_array = [ [5,[2,6,8],0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

any(isinstance(i, list) for i in np.array(board_array, dtype=object)[i])

IndexError: index 9 is out of bounds for axis 0 with size 9

In [7]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

any(isinstance(i, list) for i in np.array(board_array, dtype=object))

False

In [8]:
for i in np.array(board_array, dtype=object):
    print(i,"\n")

[5 0 0 4 6 7 3 0 9] 

[9 0 3 8 1 0 4 2 7] 

[1 7 4 2 0 3 0 0 0] 

[2 3 1 9 7 6 8 5 4] 

[8 5 7 1 2 4 0 9 0] 

[4 9 6 3 0 8 1 7 2] 

[0 0 0 0 8 9 2 6 0] 

[7 8 2 6 4 1 0 0 5] 

[0 1 0 0 0 0 7 0 8] 



In [9]:
for i in np.array(board_array, dtype=object):
    for j in range(9):
        print(i[j],"\n")

5 

0 

0 

4 

6 

7 

3 

0 

9 

9 

0 

3 

8 

1 

0 

4 

2 

7 

1 

7 

4 

2 

0 

3 

0 

0 

0 

2 

3 

1 

9 

7 

6 

8 

5 

4 

8 

5 

7 

1 

2 

4 

0 

9 

0 

4 

9 

6 

3 

0 

8 

1 

7 

2 

0 

0 

0 

0 

8 

9 

2 

6 

0 

7 

8 

2 

6 

4 

1 

0 

0 

5 

0 

1 

0 

0 

0 

0 

7 

0 

8 



In [10]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

print(any(isinstance(i, list) for i in np.array(board_array, dtype=object)))

any(isinstance(i[j], list) for i in np.array(board_array, dtype=object) and j in range(9))

False


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [11]:
board_array = [ [5,[2,4,6],0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in np.array(board_array, dtype=object):
    for j in range(2):
        print(i[j],"type:", type(i[j]))

for i in np.array(board_array, dtype=object):
        print(i,"type:", type(i))

5 type: <class 'int'>
[2, 4, 6] type: <class 'list'>
9 type: <class 'int'>
0 type: <class 'int'>
1 type: <class 'int'>
7 type: <class 'int'>
2 type: <class 'int'>
3 type: <class 'int'>
8 type: <class 'int'>
5 type: <class 'int'>
4 type: <class 'int'>
9 type: <class 'int'>
0 type: <class 'int'>
0 type: <class 'int'>
7 type: <class 'int'>
8 type: <class 'int'>
0 type: <class 'int'>
1 type: <class 'int'>
[5 list([2, 4, 6]) 0 4 6 7 3 0 9] type: <class 'numpy.ndarray'>
[9 0 3 8 1 0 4 2 7] type: <class 'numpy.ndarray'>
[1 7 4 2 0 3 0 0 0] type: <class 'numpy.ndarray'>
[2 3 1 9 7 6 8 5 4] type: <class 'numpy.ndarray'>
[8 5 7 1 2 4 0 9 0] type: <class 'numpy.ndarray'>
[4 9 6 3 0 8 1 7 2] type: <class 'numpy.ndarray'>
[0 0 0 0 8 9 2 6 0] type: <class 'numpy.ndarray'>
[7 8 2 6 4 1 0 0 5] type: <class 'numpy.ndarray'>
[0 1 0 0 0 0 7 0 8] type: <class 'numpy.ndarray'>


In [12]:
any(isinstance(i, np.ndarray) for i in np.array(board_array, dtype=object))

True

In [13]:
board_array = [ [5,[2,4,6],0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

x = []

for i in np.array(board_array, dtype=object):
    for j in range(9):
        #print(i[j], type(i[j]))
        #print(isinstance(i[j], list))
        x.append(isinstance(i[j], list))

print(x,"\n") 

print(any(i for i in x))

[False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False] 

True


In [14]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

x = []

for i in np.array(board_array, dtype=object):
    for j in range(9):
        #print(i[j], type(i[j]))
        #print(isinstance(i[j], list))
        x.append(isinstance(i[j], list))

print(x,"\n")

print(any(i for i in x))

[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False] 

False


In [19]:
def sudoku_solver(board):
    add_possibilities(board_array)
    print("BOARD!!", board_array)
    print(np.array(board_array, dtype=object))
    
    fill_box(board_array)
    print("BOARD!!", board_array)
    print("\n"*2,np.array(board_array, dtype=object))

    remove_possibilities(board_array)
    print("BOARD!!", board_array)
    print("\n"*2,np.array(board_array, dtype=object))
    
    x = []

    for i in np.array(board_array, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))

    if any(i for i in x) is True:
        sudoku_solver(board)
    else:
        print("\n"*2,np.array(board_array, dtype=object))

In [20]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

sudoku_solver(board_array)

BOARD!! [[5, [2], [8], 4, 6, 7, 3, [1, 8], 9], [9, [6], 3, 8, 1, [5], 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], [8], [6]], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, [6], 9, [3, 6]], [4, 9, 6, 3, [5], 8, 1, 7, 2], [[3], [4], [5], [5, 7], 8, 9, 2, 6, [1, 3]], [7, 8, 2, 6, 4, 1, [9], [3], 5], [[3, 6], 1, [5, 9], [5], [3, 5, 9], [2, 5], 7, [3, 4], 8]]
[[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6, 9]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5, 9]) list([2, 5]) 7
  list([3, 4]) 8]]
BOARD!! [[5, 2, 8, 4, 6, 7, 3, [1, 8], 9], [9, 6, 3, 8, 1, 5, 4, 2, 7], [1, 7, 4, 2, [5, 9], 3, [5, 6, 9], 8, 6], [2, 3, 1, 9, 7, 6, 8, 5, 4], [8, 5, 7, 1, 2, 4, 6, 9, [3, 6]], [4, 9, 6, 3, 5, 8, 1, 7, 2], [3, 