Figure out how to loop so that you check all the square values

In [3]:
import numpy as np

In [10]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# squares

# first square
print(np.array(board_array)[0:3, 0:3])

# middle square
print(np.array(board_array)[3:6, 3:6])

for i in [0,3,6]:
    for j in [0,3,6]:
        print(np.array(board_array)[i:i+3, j:j+3])

[[5 0 0]
 [9 0 3]
 [1 7 4]]
[[9 7 6]
 [1 2 4]
 [3 0 8]]
[[5 0 0]
 [9 0 3]
 [1 7 4]]
[[4 6 7]
 [8 1 0]
 [2 0 3]]
[[3 0 9]
 [4 2 7]
 [0 0 0]]
[[2 3 1]
 [8 5 7]
 [4 9 6]]
[[9 7 6]
 [1 2 4]
 [3 0 8]]
[[8 5 4]
 [0 9 0]
 [1 7 2]]
[[0 0 0]
 [7 8 2]
 [0 1 0]]
[[0 8 9]
 [6 4 1]
 [0 0 0]]
[[2 6 0]
 [0 0 5]
 [7 0 8]]


In [33]:
def add_possibilities(board_array):
    if board_array[j][k] == 0:
        if board_array[j][k] != i:
            board_array[j][k] = []
            board_array[j][k].append(i)
    elif isinstance(board_array[j][k],list) and i not in board_array[j][k]:
        board_array[j][k].append(i)    

In [34]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

for i in range(1,10):
    for j in range(3):
        for k in range(6):
            if j <=2:
                if k <=2:
                    if i not in np.array(board_array)[0:3, 0:3]:
                        add_possibilities(board_array)
                elif k <=5 and k > 2:
                    if i not in np.array(board_array)[0:3, 3:6]:
                        add_possibilities(board_array)

print(np.array(board_array))                                    

[[5 list([2, 6, 8]) list([2, 6, 8]) 4 6 7 3 0 9]
 [9 list([2, 6, 8]) 3 8 1 list([5, 9]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 0 0 0]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 0 9 0]
 [4 9 6 3 0 8 1 7 2]
 [0 0 0 0 8 9 2 6 0]
 [7 8 2 6 4 1 0 0 5]
 [0 1 0 0 0 0 7 0 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\532643176.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[0:3, 0:3]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\532643176.py:22: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[0:3, 3:6]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\532643176.py:30: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is 

In [19]:
1 not in np.array(board_array)[0:3][0:3]

C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\247817103.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  1 not in np.array(board_array)[0:3][0:3]


False

In [20]:
2 not in np.array(board_array)[0:3][0:3]

C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\355059937.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  2 not in np.array(board_array)[0:3][0:3]


False

In [25]:
for i in range(9):
    print(np.array(board_array, dtype=object)[i])

[5 0 0 4 6 7 3 0 9]
[9 0 3 8 1 list([1, 2, 3, 4, 5, 6, 7, 8, 9]) 4 2 7]
[1 7 4 2 list([1, 2, 3, 4, 5, 6, 7, 8, 9]) 3 0 0 0]
[2 3 1 9 7 6 8 5 4]
[8 5 7 1 2 4 0 9 0]
[4 9 6 3 0 8 1 7 2]
[0 0 0 0 8 9 2 6 0]
[7 8 2 6 4 1 0 0 5]
[0 1 0 0 0 0 7 0 8]


In [26]:
print(np.array(board_array, dtype=object)[:][0])

[5 0 0 4 6 7 3 0 9]


In [27]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

print(row[0] for row in board_array)

<generator object <genexpr> at 0x0000022B892F0970>


In [35]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]


for i in range(1,10):
    for j in range(9):
        for k in range(9):
                    if j <=3:
                        if k <=3:
                            if i not in np.array(board_array)[0:3, 0:3]:
                                add_possibilities(board_array)
                        elif k <=6 and k > 3:
                            if i not in np.array(board_array)[0:3, 3:6]:
                                add_possibilities(board_array)
                        elif k <=9 and k > 6:
                            if i not in np.array(board_array)[0:3, 6:9]:
                                add_possibilities(board_array)
                    elif j <=6 and j > 3:
                        if k <=3:
                            if i not in np.array(board_array)[3:6, 0:3]:
                                add_possibilities(board_array)
                        elif k <=6 and k > 3:
                            if i not in np.array(board_array)[3:6, 3:6]:
                                add_possibilities(board_array)
                        elif k <=9 and k > 6:
                            if i not in np.array(board_array)[3:6, 6:9]:
                                add_possibilities(board_array)
                    elif j <=9 and j > 6:
                        if k <=3:
                            if i not in np.array(board_array)[6:9, 0:3]:
                                add_possibilities(board_array)
                        elif k <=6 and k > 3:
                            if i not in np.array(board_array)[6:9, 3:6]:
                                add_possibilities(board_array)
                        elif k <=9 and k > 6:
                            if i not in np.array(board_array)[6:9, 6:9]:
                                add_possibilities(board_array)
                                
print(np.array(board_array))

[[5 list([2, 6, 8]) list([2, 6, 8]) 4 6 7 3 list([1, 5, 6, 8]) 9]
 [9 list([2, 6, 8]) 3 8 1 list([5, 9]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 9]) list([1, 5, 6, 8])
  list([1, 5, 6, 8])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([5]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [0 0 0 0 8 9 2 6 list([3, 6])]
 [7 8 2 6 4 1 list([2, 3, 5, 7]) list([1, 3, 4, 9]) 5]
 [list([3, 4, 5, 6, 9]) 1 list([3, 4, 5, 6, 9]) list([3, 4, 5, 6, 9])
  list([2, 3, 5, 7]) list([2, 3, 5, 7]) 7 list([1, 3, 4, 9]) 8]]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\3710534419.py:26: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[0:3, 6:9]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\3710534419.py:20: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if i not in np.array(board_array)[0:3, 0:3]:
C:\Users\Daniel\AppData\Local\Temp\ipykernel_15944\3710534419.py:23: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) 

In [37]:
board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]


for i in range(1,10):
    for j in range(9):
        for k in range(9):
                    if j <=3:
                        if k <=3:
                            if i not in np.array(board_array,dtype=object)[0:3, 0:3]:
                                add_possibilities(board_array)
                        elif k <=6 and k > 3:
                            if i not in np.array(board_array,dtype=object)[0:3, 3:6]:
                                add_possibilities(board_array)
                        elif k <=9 and k > 6:
                            if i not in np.array(board_array,dtype=object)[0:3, 6:9]:
                                add_possibilities(board_array)
                    elif j <=6 and j > 3:
                        if k <=3:
                            if i not in np.array(board_array,dtype=object)[3:6, 0:3]:
                                add_possibilities(board_array)
                        elif k <=6 and k > 3:
                            if i not in np.array(board_array,dtype=object)[3:6, 3:6]:
                                add_possibilities(board_array)
                        elif k <=9 and k > 6:
                            if i not in np.array(board_array,dtype=object)[3:6, 6:9]:
                                add_possibilities(board_array)
                    elif j <=9 and j > 6:
                        if k <=3:
                            if i not in np.array(board_array,dtype=object)[6:9, 0:3]:
                                add_possibilities(board_array)
                        elif k <=6 and k > 3:
                            if i not in np.array(board_array,dtype=object)[6:9, 3:6]:
                                add_possibilities(board_array)
                        elif k <=9 and k > 6:
                            if i not in np.array(board_array,dtype=object)[6:9, 6:9]:
                                add_possibilities(board_array)
                                
print(np.array(board_array,dtype=object))

[[5 list([2, 6, 8]) list([2, 6, 8]) 4 6 7 3 list([1, 5, 6, 8]) 9]
 [9 list([2, 6, 8]) 3 8 1 list([5, 9]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 9]) list([1, 5, 6, 8])
  list([1, 5, 6, 8])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([5]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [0 0 0 0 8 9 2 6 list([3, 6])]
 [7 8 2 6 4 1 list([2, 3, 5, 7]) list([1, 3, 4, 9]) 5]
 [list([3, 4, 5, 6, 9]) 1 list([3, 4, 5, 6, 9]) list([3, 4, 5, 6, 9])
  list([2, 3, 5, 7]) list([2, 3, 5, 7]) 7 list([1, 3, 4, 9]) 8]]


In [38]:
if j <=3:
    if k <=3:
        if i not in np.array(board_array,dtype=object)[0:3, 0:3]:
    elif k <=6 and k > 3:
        if i not in np.array(board_array,dtype=object)[0:3, 3:6]:
    elif k <=9 and k > 6:
        if i not in np.array(board_array,dtype=object)[0:3, 6:9]:
elif j <=6 and j > 3:
    if k <=3:
        if i not in np.array(board_array,dtype=object)[3:6, 0:3]:
    elif k <=6 and k > 3:
        if i not in np.array(board_array,dtype=object)[3:6, 3:6]:
    elif k <=9 and k > 6:
        if i not in np.array(board_array,dtype=object)[3:6, 6:9]:
elif j <=9 and j > 6:
    if k <=3:
        if i not in np.array(board_array,dtype=object)[6:9, 0:3]:
    elif k <=6 and k > 3:
        if i not in np.array(board_array,dtype=object)[6:9, 3:6]:
    elif k <=9 and k > 6:
        if i not in np.array(board_array,dtype=object)[6:9, 6:9]:

IndentationError: expected an indented block (3053004444.py, line 4)

In [ ]:
if j <=3:
    if k <=3:
        if i not in np.array(board_array,dtype=object)[0:3, 0:3]:
            add_possibilities(board_array)
    elif k <=6 and k > 3:
        if i not in np.array(board_array,dtype=object)[0:3, 3:6]:
            add_possibilities(board_array)
    elif k <=9 and k > 6:
        if i not in np.array(board_array,dtype=object)[0:3, 6:9]:
            add_possibilities(board_array)
elif j <=6 and j > 3:
    if k <=3:
        if i not in np.array(board_array,dtype=object)[3:6, 0:3]:
            add_possibilities(board_array)
    elif k <=6 and k > 3:
        if i not in np.array(board_array,dtype=object)[3:6, 3:6]:
            add_possibilities(board_array)
    elif k <=9 and k > 6:
        if i not in np.array(board_array,dtype=object)[3:6, 6:9]:
            add_possibilities(board_array)
elif j <=9 and j > 6:
    if k <=3:
        if i not in np.array(board_array,dtype=object)[6:9, 0:3]:
            add_possibilities(board_array)
    elif k <=6 and k > 3:
        if i not in np.array(board_array,dtype=object)[6:9, 3:6]:
            add_possibilities(board_array)
    elif k <=9 and k > 6:
        if i not in np.array(board_array,dtype=object)[6:9, 6:9]:
            add_possibilities(board_array)