### Version 2: With squares

Incorporates 3x3 box check on top of the row and column check before filling in a number as a possibility.
This means there are fewer possibilities in the boxes and so the board can be solved in less steps.
Can solve slightly harder sudokus than version 1 but is still limited.

In [2]:
import numpy as np

In [15]:
# Helper function used in the add all possibilities function below.
# This is added in version 2 of the solver to aid with checking through each square
def add_possibility(board, i, j, k):
    if board[j][k] == 0:
        if board[j][k] != i:
            board[j][k] = []
            board[j][k].append(i)
    elif isinstance(board[j][k],list) and i not in board[j][k]:
        board[j][k].append(i)

# Iterate over each square. This can be tidied up to loop through all the 3x3 squares instead of hardcoding it for each one.
def add_all_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                    if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                        if j <= 2:
                            if k <= 2:
                                if i not in np.array(board,dtype=object)[0:3, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[0:3, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[0:3, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=5 and j > 2:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[3:6, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[3:6, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[3:6, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=8 and j > 5:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[6:9, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[6:9, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[6:9, 6:9]:
                                    add_possibility(board,i,j,k)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibility(board, i, j, k):
    if isinstance(board[j][k],list) and i in board[j][k]:
        board[j][k].remove(i)

def remove_row_column_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    remove_possibility(board,i,j,k)

def remove_square_possibilities(board):
    for i in range(1,10):
            for j in range(9):
                for k in range(9):
                    if j <= 2:
                        if k <= 2:
                            if i in np.array(board,dtype=object)[0:3, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[0:3, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[0:3, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=5 and j > 2:
                        if k <=2:
                            if i in np.array(board,dtype=object)[3:6, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[3:6, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[3:6, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=8 and j > 5:
                        if k <=2:
                            if i in np.array(board,dtype=object)[6:9, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[6:9, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[6:9, 6:9]:
                                remove_possibility(board,i,j,k)    
                                
def single_row_number(board):
    for k in range(9):
        zero_counter = [0,0,0,0,0,0,0,0,0]

        for i in range(9):
            if isinstance(board[k][i], list):
                for j in range(9):
                    zero_counter[j] += board[k][i].count(j+1)
        #print("\n",zero_counter)

        #print("\nSecond loop\n")

        for j in range(9):
            if zero_counter[j] == 1:
                zero_counter[j] = 0
                for i in range(9):
                    if isinstance(board[k][i], list):
                        zero_counter[j] += board[k][i].count(j+1)
                        #print("\ncounter for number", j+1,"is", zero_counter[j])
                    if zero_counter[j] == 1:
                        board[k][i] = j+1
                        #print("\nThe new value of row 9, column",j+1, "is",board[k][i])
                        break
     

In [16]:
def sudoku_solver(board):
    # counter variable "n" used to check how many times we need to call the function to solve the puzzle
    global n
    
    add_all_possibilities(board)
    #print(np.array(board, dtype=object))
    
    fill_box(board)
    #print("\n"*2,np.array(board, dtype=object))

    remove_row_column_possibilities(board)
    #print("\n"*2,np.array(board, dtype=object))
    
    remove_square_possibilities(board)
    #print("\n"*2,np.array(board, dtype=object))
    
    single_row_number(board)

    # Produce an array with values True or False depending on whether any of the boxes contain a list of possibilities or not
    # If we still have lists, then we've got work to do so we have to run the function again.

    x = []
    
    for i in np.array(board, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))

    # If there are any True values - i.e. lists that have possible numbers in them, then repeat the loop again.
    if any(i for i in x) is True:
        print("\nThe current board is:\n",np.array(board, dtype=object))
        # Increase the counter by 1
        n += 1
        sudoku_solver(board)
    # Else if there are no lists left... The puzzle is solved!
    else:
        print("\nSolved in", n+1, "function calls!")
        print("\nThe final board is:\n",np.array(board, dtype=object))

In [17]:
# Super easy board
# Same board we started with in version 1 - website: https://www.puzzles-to-print.com/printable-sudokus/sudokus-for-kids/beginner-sudoku-easy.shtml
# Let's see if we can solve this one even more quickly

board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


Solved in 1 function calls!

The final board is:
 [[5 2 8 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 5 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 6 9 3]
 [4 9 6 3 5 8 1 7 2]
 [3 4 5 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 5 3 2 7 4 8]]


In version 1 the above board was solved in 3 function calls. 
So by looking at the squares we limit the amount possible numbers we can put in our temporary lists, and we improve the amount of numbers we can remove once we fill in the boxes with only 1 number in their list. These two components are the reason we were able to solve this easy board in 1 less call!

In [18]:
board_array = [ [0,5,0, 0,0,3, 7,0,0],
                [8,3,1, 4,2,7, 0,0,5],
                [9,7,4, 0,8,6, 1,2,3],
               
                [3,8,6, 1,4,0, 2,5,7],
                [7,0,5, 0,0,0, 0,0,0],
                [0,4,9, 7,0,2, 8,3,6],
               
                [5,0,0, 0,7,4, 0,9,8],
                [0,9,0, 3,0,1, 0,0,2],
                [2,0,0, 0,9,0, 3,0,1]
                ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


The currect board is:
 [[6 5 2 9 1 3 7 8 list([4])]
 [8 3 1 4 2 7 9 6 5]
 [9 7 4 5 8 6 1 2 3]
 [3 8 6 1 4 9 2 5 7]
 [7 2 5 list([6, 8]) 3 list([8]) list([4, 9]) 1 list([4, 9])]
 [1 4 9 7 5 2 8 3 6]
 [5 1 3 2 7 4 6 9 8]
 [list([4]) 9 8 3 6 1 5 list([4, 7]) 2]
 [2 6 list([7, 8]) list([8]) 9 5 3 4 1]]

Solved in 2 function calls!

The final board is:
 [[6 5 2 9 1 3 7 8 4]
 [8 3 1 4 2 7 9 6 5]
 [9 7 4 5 8 6 1 2 3]
 [3 8 6 1 4 9 2 5 7]
 [7 2 5 6 3 8 4 1 9]
 [1 4 9 7 5 2 8 3 6]
 [5 1 3 2 7 4 6 9 8]
 [4 9 8 3 6 1 5 7 2]
 [2 6 7 8 9 5 3 4 1]]


Similar result here. In this case needing only 4 function calls, compared to 6 in version 1, to solve the puzzle. An improvement indeed!

Now let's try something a bit harder.

The below puzzle was taken from here: https://www.rd.com/wp-content/uploads/2020/12/Sudoku-Puzzle_08.pdf
This website also offers 19 other sudoku puzzles at different levels in case you like to test your skills (or the algorithm's skills for that matter): https://www.rd.com/list/printable-sudoku-puzzles/

In [19]:
# Medium sudoku

board_array = [ [1,5,0, 2,0,9, 0,0,4],
                [0,4,0, 0,0,6, 0,0,0],
                [0,0,0, 0,4,0, 0,6,3],
                
                [0,7,0, 0,0,0, 8,0,6],
                [6,0,0, 0,0,0, 0,0,5],
                [2,0,8, 0,0,0, 0,1,0],
               
                [4,6,0, 0,8,0, 0,0,0],
                [0,0,0, 6,0,0, 0,7,0],
                [8,0,0, 5,0,1, 0,4,9],
              ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


The currect board is:
 [[1 5 6 2 list([3]) 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) 8 list([1, 3, 5, 7]) 6
  list([1, 2, 5, 9]) list([2, 5, 9]) list([1, 2])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 list([3, 4, 5]) list([3, 4, 9]) 1 7]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6
  list([2, 3, 9]) 4 list([1, 2, 3, 5]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 3, 7]) 1 6 4 9]]

The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) 8 list([1, 5


The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])
  list([1, 2, 7, 9]) 8 list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([1, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3])
  list([1, 2, 3]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5]) list([1, 2, 3, 9]) list([1, 3, 5, 9]) 6 list([2, 9]) 4
  list([1, 2, 3]) 7 8]
 [8 list([2, 3]) list([3, 7]) 5 list([2, 7]) 1 6 4 9]]

The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])



The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])
  list([1, 2, 7, 9]) 8 list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([1, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3])
  list([1, 2, 3]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5]) list([1, 2, 3, 9]) list([1, 3, 5, 9]) 6 list([2, 9]) 4
  list([1, 2, 3]) 7 8]
 [8 list([2, 3]) list([3, 7]) 5 list([2, 7]) 1 6 4 9]]

The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])



The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])
  list([1, 2, 7, 9]) 8 list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([1, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3])
  list([1, 2, 3]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5]) list([1, 2, 3, 9]) list([1, 3, 5, 9]) 6 list([2, 9]) 4
  list([1, 2, 3]) 7 8]
 [8 list([2, 3]) list([3, 7]) 5 list([2, 7]) 1 6 4 9]]

The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])



The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])
  list([1, 2, 7, 9]) 8 list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([1, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3])
  list([1, 2, 3]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5]) list([1, 2, 3, 9]) list([1, 3, 5, 9]) 6 list([2, 9]) 4
  list([1, 2, 3]) 7 8]
 [8 list([2, 3]) list([3, 7]) 5 list([2, 7]) 1 6 4 9]]

The currect board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 7]) 4 list([3, 7]) 8 5 6 list([1, 2, 9]) list([2, 9])
  list([1, 2])]
 [9 8 2 1 4 7 5 6 3]
 [list([3, 5]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([3, 4, 7, 9])


KeyboardInterrupt: 

This result may not seem encouraging at first, but if we compare it to version one, we can see the progress made.

For starters, the first row is completely solved! The solution being:

"1, 5, 6, 2, 3, 9, 7, 8, 4".

Compare this with our petty attempt where we  couldn't reach further than:

"1, 5, [3, 6 or 7], 2, [3, 6 or 7], 9, [3, 6 or 7], [3 or 8], 4".

This result should give us a good pat on the back.

Though in any case, we have work to do so jump at version 3 to see some improvements!

I've left the expert level sudoku from V1 here in case you wanted to see the improvements in the result :)

In [ ]:
# Expert level sudoku
# We are not close to solving this quite yet
# board_array = [ [0,9,0, 0,0,0, 8,3,0],
#                 [0,0,3, 6,0,0, 0,4,0],
#                 [0,0,8, 0,0,0, 0,0,0],
                
#                 [2,0,0, 0,9,0, 0,0,0],
#                 [0,0,0, 4,3,8, 0,0,0],
#                 [9,0,5, 0,6,0, 0,0,0],
               
#                 [0,0,0, 7,0,0, 9,0,0],
#                 [0,0,0, 0,0,4, 0,0,6],
#                 [1,7,0, 0,0,0, 0,0,5],
#               ]
# # Start a counter to see how many times you need to call the function to solve the puzzle
# n = 0
# sudoku_solver(board_array)

In [45]:
# Helper function used in the add all possibilities function below.
# This is added in version 2 of the solver to aid with checking through each square
def add_possibility(board, i, j, k):
    if board[j][k] == 0:
        if board[j][k] != i:
            board[j][k] = []
            board[j][k].append(i)
    elif isinstance(board[j][k],list) and i not in board[j][k]:
        board[j][k].append(i)

# Iterate over each square. This can be tidied up to loop through all the 3x3 squares instead of hardcoding it for each one.
def add_all_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                    if i not in board[j] and i not in np.array(board, dtype=object)[:,k]:
                        if j <= 2:
                            if k <= 2:
                                if i not in np.array(board,dtype=object)[0:3, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[0:3, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[0:3, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=5 and j > 2:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[3:6, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[3:6, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[3:6, 6:9]:
                                    add_possibility(board,i,j,k)
                        elif j <=8 and j > 5:
                            if k <=2:
                                if i not in np.array(board,dtype=object)[6:9, 0:3]:
                                    add_possibility(board,i,j,k)
                            elif k <=5 and k > 2:
                                if i not in np.array(board,dtype=object)[6:9, 3:6]:
                                    add_possibility(board,i,j,k)
                            elif k <=8 and k > 5:
                                if i not in np.array(board,dtype=object)[6:9, 6:9]:
                                    add_possibility(board,i,j,k)

def fill_box(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if isinstance(board[j][k], list) and len(board[j][k]) == 1:
                    board[j][k] = board[j][k][0]

def remove_possibility(board, i, j, k):
    if isinstance(board[j][k],list) and i in board[j][k]:
        board[j][k].remove(i)

def remove_row_column_possibilities(board):
    for i in range(1,10):
        for j in range(9):
            for k in range(9):
                if i in board[j] or i in np.array(board, dtype=object)[:,k]:
                    remove_possibility(board,i,j,k)

def remove_square_possibilities(board):
    for i in range(1,10):
            for j in range(9):
                for k in range(9):
                    if j <= 2:
                        if k <= 2:
                            if i in np.array(board,dtype=object)[0:3, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[0:3, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[0:3, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=5 and j > 2:
                        if k <=2:
                            if i in np.array(board,dtype=object)[3:6, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[3:6, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[3:6, 6:9]:
                                remove_possibility(board,i,j,k)
                    elif j <=8 and j > 5:
                        if k <=2:
                            if i in np.array(board,dtype=object)[6:9, 0:3]:
                                remove_possibility(board,i,j,k)
                        elif k <=5 and k > 2:
                            if i in np.array(board,dtype=object)[6:9, 3:6]:
                                remove_possibility(board,i,j,k)
                        elif k <=8 and k > 5:
                            if i in np.array(board,dtype=object)[6:9, 6:9]:
                                remove_possibility(board,i,j,k)  

def single_row_number(board):
    for k in range(9):
        
        # Initialise a counter for each number 1-9 and count how many times they appear in the row
        zero_counter = [0,0,0,0,0,0,0,0,0]

        for i in range(9):
            # If the object in the row is a list, then add one to the counter each time the number is spotted
            if isinstance(board[k][i], list):
                for j in range(9):
                    zero_counter[j] += board[k][i].count(j+1)
        
        # If the counter reached exactly one, bingo! We can fill that box with the number as it's not possible to place it anywhere else in the row
        for j in range(9):
            if zero_counter[j] == 1:
                zero_counter[j] = 0
                for i in range(9):
                    if isinstance(board[k][i], list):
                        zero_counter[j] += board[k][i].count(j+1)
                        #print("\ncounter for number", j+1,"is", zero_counter[j])
                    if zero_counter[j] == 1:
                        board[k][i] = (j+1)
                        #print("\nThe new value of row 9, column",j+1, "is",board[k][i])
                        break
                             
                                
def single_column_number(board):
    zero_counter = [0,0,0,0,0,0,0,0,0]

    for i in range(9):
        if isinstance(board[i][8], list):
            for j in range(9):
                zero_counter[j] += board[i][8].count(j+1)
    #print("\n",zero_counter)

    #print("\nSecond loop\n")

    for j in range(9):
        if zero_counter[j] == 1:
            zero_counter[j] = 0
            for i in range(9):
                if isinstance(board[i][8], list):
                    zero_counter[j] += board[i][8].count(j+1)
                    #print("\ncounter for number", j+1,"is", zero_counter[j])
                if zero_counter[j] == 1:
                    board[i][8] = j+1
                    #print("\nThe new value of row 9, column",j+1, "is",board[i][8])
                    break    


def recursive_solve(board,n):
    single_row_number(board)
    print("\nFind and sub single numbers in row:\n",np.array(board, dtype=object))
    single_column_number(board)
    print("\nFind and sub single numbers in column:\n",np.array(board, dtype=object))
    
    fill_box(board)
    print("\nFill box again:\n",np.array(board, dtype=object))
    
    remove_row_column_possibilities(board)
    print("\nRemove row and column possibilities:\n",np.array(board, dtype=object))
    remove_square_possibilities(board)
    print("\nRemove square possibilities:\n",np.array(board, dtype=object))
    
    print("\nThe current board is:\n",np.array(board, dtype=object))
    
    # Produce an array with values True or False depending on whether any of the boxes contain a list of possibilities or not
    # If we still have lists, then we've got work to do so we have to run the function again.
    x = []
    
    for i in np.array(board, dtype=object):
        for j in range(9):
            x.append(isinstance(i[j], list))

    # If there are any True values - i.e. lists that have possible numbers in them, then repeat the loop again.
    if any(i for i in x) is True:
        print("\nThe current board is:\n",np.array(board, dtype=object))
        # Increase the counter by 1
        n += 1
        sudoku_solver(board)
    # Else if there are no lists left... The puzzle is solved!
    else:
        print("\nSolved in", n+1, "function calls!")
        print("\nThe final board is:\n",np.array(board, dtype=object))

In [46]:
def sudoku_solver(board):
    # counter variable "n" used to check how many times we need to call the function to solve the puzzle
    add_all_possibilities(board)
    print("\nThe initial board is:\n",np.array(board, dtype=object))

    n = 0

    recursive_solve(board,n)

In [47]:
# Super easy board
# Same board we started with in version 1 - website: https://www.puzzles-to-print.com/printable-sudokus/sudokus-for-kids/beginner-sudoku-easy.shtml
# Let's see if we can solve this one even more quickly

board_array = [ [5,0,0, 4,6,7, 3,0,9],
                [9,0,3, 8,1,0, 4,2,7],
                [1,7,4, 2,0,3, 0,0,0],

                [2,3,1, 9,7,6, 8,5,4],
                [8,5,7, 1,2,4, 0,9,0],
                [4,9,6, 3,0,8, 1,7,2],

                [0,0,0, 0,8,9, 2,6,0],
                [7,8,2, 6,4,1, 0,0,5],
                [0,1,0, 0,0,0, 7,0,8]
                ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


The initial board is:
 [[5 list([2]) list([8]) 4 6 7 3 list([1, 8]) 9]
 [9 list([6]) 3 8 1 list([5]) 4 2 7]
 [1 7 4 2 list([5, 9]) 3 list([5, 6]) list([8]) list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 list([3, 6])]
 [4 9 6 3 list([5]) 8 1 7 2]
 [list([3]) list([4]) list([5]) list([5, 7]) 8 9 2 6 list([1, 3])]
 [7 8 2 6 4 1 list([9]) list([3]) 5]
 [list([3, 6]) 1 list([5, 9]) list([5]) list([3, 5]) list([2, 5]) 7
  list([3, 4]) 8]]

Find and sub single numbers in row:
 [[5 2 list([8]) 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 list([5, 6]) 8 list([6])]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 3]
 [4 9 6 3 5 8 1 7 2]
 [list([3]) 4 list([5]) 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 [6 1 9 list([5]) list([3, 5]) 2 7 4 8]]

Find and sub single numbers in column:
 [[5 2 list([8]) 4 6 7 3 1 9]
 [9 6 3 8 1 5 4 2 7]
 [1 7 4 2 9 3 list([5, 6]) 8 6]
 [2 3 1 9 7 6 8 5 4]
 [8 5 7 1 2 4 list([6]) 9 3]
 [4 9 6 3 5 8 1 7 2]
 [list([3]) 4 list([5]) 7 8 9 2 6 1]
 [7 8 2 6 4 1 9 3 5]
 

In [48]:
board_array = [ [0,5,0, 0,0,3, 7,0,0],
                [8,3,1, 4,2,7, 0,0,5],
                [9,7,4, 0,8,6, 1,2,3],
               
                [3,8,6, 1,4,0, 2,5,7],
                [7,0,5, 0,0,0, 0,0,0],
                [0,4,9, 7,0,2, 8,3,6],
               
                [5,0,0, 0,7,4, 0,9,8],
                [0,9,0, 3,0,1, 0,0,2],
                [2,0,0, 0,9,0, 3,0,1]
                ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


The initial board is:
 [[list([6]) 5 list([2]) list([9]) list([1]) 3 7 list([4, 6, 8])
  list([4, 9])]
 [8 3 1 4 2 7 list([6, 9]) list([6]) 5]
 [9 7 4 list([5]) 8 6 1 2 3]
 [3 8 6 1 4 list([9]) 2 5 7]
 [7 list([1, 2]) 5 list([6, 8, 9]) list([3, 6]) list([8, 9]) list([4, 9])
  list([1, 4]) list([4, 9])]
 [list([1]) 4 9 7 list([5]) 2 8 3 6]
 [5 list([1, 6]) list([3]) list([2, 6]) 7 4 list([6]) 9 8]
 [list([4, 6]) 9 list([7, 8]) 3 list([5, 6]) 1 list([4, 5, 6])
  list([4, 6, 7]) 2]
 [2 list([6]) list([7, 8]) list([5, 6, 8]) 9 list([5, 8]) 3
  list([4, 6, 7]) 1]]

Find and sub single numbers in row:
 [[list([6]) 5 2 list([9]) 1 3 7 8 list([4, 9])]
 [8 3 1 4 2 7 9 list([6]) 5]
 [9 7 4 5 8 6 1 2 3]
 [3 8 6 1 4 9 2 5 7]
 [7 2 5 list([6, 8, 9]) 3 list([8, 9]) list([4, 9]) list([1, 4])
  list([4, 9])]
 [1 4 9 7 5 2 8 3 6]
 [5 1 3 2 7 4 list([6]) 9 8]
 [list([4, 6]) 9 8 3 list([5, 6]) 1 list([4, 5, 6]) list([4, 6, 7]) 2]
 [2 list([6]) list([7, 8]) list([5, 6, 8]) 9 list([5, 8]) 3 4 1]]

Find an

In [49]:
# Medium sudoku

board_array = [ [1,5,0, 2,0,9, 0,0,4],
                [0,4,0, 0,0,6, 0,0,0],
                [0,0,0, 0,4,0, 0,6,3],
                
                [0,7,0, 0,0,0, 8,0,6],
                [6,0,0, 0,0,0, 0,0,5],
                [2,0,8, 0,0,0, 0,1,0],
               
                [4,6,0, 0,8,0, 0,0,0],
                [0,0,0, 6,0,0, 0,7,0],
                [8,0,0, 5,0,1, 0,4,9],
              ]

# Start a counter to see how many times you need to call the function to solve the puzzle
n = 0
sudoku_solver(board_array)


The initial board is:
 [[1 5 list([3, 6, 7]) 2 list([3, 7]) 9 list([7]) list([8]) 4]
 [list([3, 7, 9]) 4 list([2, 3, 7, 9]) list([1, 3, 7, 8])
  list([1, 3, 5, 7]) 6 list([1, 2, 5, 7, 9]) list([2, 5, 8, 9])
  list([1, 2, 7, 8])]
 [list([7, 9]) list([2, 8, 9]) list([2, 7, 9]) list([1, 7, 8]) 4
  list([5, 7, 8]) list([1, 2, 5, 7, 9]) 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([1, 3, 4, 9])
  list([1, 2, 3, 5, 9]) list([2, 3, 4, 5]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) list([1, 3, 4, 7, 8, 9])
  list([1, 2, 3, 7, 9]) list([2, 3, 4, 7, 8]) list([2, 3, 4, 7, 9])
  list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 7, 9]) list([3, 5, 6, 7, 9])
  list([3, 4, 5, 7]) list([3, 4, 7, 9]) 1 list([7])]
 [4 6 list([1, 2, 3, 5, 7, 9]) list([3, 7, 9]) 8 list([2, 3, 7])
  list([1, 2, 3, 5]) list([2, 3, 5]) list([1, 2])]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6
  list([2, 3, 9]) list([2, 3, 4]) list([1, 2, 3, 5]) 7 list([1, 2, 8])]
 [8 list([2, 3]) lis


Remove row and column possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9


Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The current board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 


Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The current board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 


Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The current board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 


Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The current board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 

 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The initial board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  


Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The current board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 

 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

Remove row and column possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2,


The initial board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

Find and sub single numbers in row:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list(


Remove square possibilities:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

The current board is:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 

 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1, 2, 7, 9])
  list([2, 3, 7]) list([2, 3, 4, 9]) list([2, 3, 9]) 5]
 [2 list([3, 9]) 8 list([3, 4, 9]) 6 5 list([3, 4, 9]) 1 7]
 [4 6 list([2, 3, 5, 7, 9]) list([3, 9]) 8 list([2, 3, 7]) list([2, 3])
  list([2, 3, 5]) 1]
 [list([3, 5, 9]) list([1, 2, 3, 9]) list([1, 2, 3, 5, 9]) 6 list([2, 9])
  4 list([2, 3]) 7 8]
 [8 list([2, 3]) list([2, 3, 7]) 5 list([2, 7]) 1 6 4 9]]

Find and sub single numbers in row:
 [[1 5 6 2 3 9 7 8 4]
 [list([3, 9]) 4 list([2, 3, 9]) 7 5 6 1 list([2, 9]) 8]
 [list([7, 9]) list([2, 9]) list([2, 7, 9]) 1 4 8 5 6 3]
 [list([3, 5, 9]) 7 list([1, 3, 4, 5, 9]) list([3, 4, 9]) list([1, 2, 9])
  list([2, 3]) 8 list([2, 3, 9]) 6]
 [6 list([1, 3, 9]) list([1, 3, 4, 9]) 8 list([1

KeyboardInterrupt: 

In [54]:
board1 = [[1, 5, 6, 2, [3, 7], 9, [7], 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], [1, 3, 7, 8], [1, 3, 5, 7], 6, [1, 2, 5, 7, 9], [2, 5, 8, 9], [1, 2, 7, 8]], [[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 7, 9], 6, 3], [[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 3, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6], [6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 3, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 7, 9], [2, 3, 9], 5], [2, [3, 9], 8, [3, 4, 7, 9], 6, [3, 4, 5, 7], [3, 4, 7, 9], 1, [7]], [4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]], [[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 3, 9], 4, [1, 2, 3, 5], 7, 8], [8, [2, 3], [2, 3, 7], 5, [2, 3, 7], 1, 6, 4, 9]]

for i in board1:
    print(i,"\n")

[1, 5, 6, 2, [3, 7], 9, [7], 8, 4] 

[[3, 7, 9], 4, [2, 3, 7, 9], [1, 3, 7, 8], [1, 3, 5, 7], 6, [1, 2, 5, 7, 9], [2, 5, 8, 9], [1, 2, 7, 8]] 

[[7, 9], [2, 8, 9], [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 7, 9], 6, 3] 

[[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 3, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6] 

[6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 3, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 7, 9], [2, 3, 9], 5] 

[2, [3, 9], 8, [3, 4, 7, 9], 6, [3, 4, 5, 7], [3, 4, 7, 9], 1, [7]] 

[4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]] 

[[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 3, 9], 4, [1, 2, 3, 5], 7, 8] 

[8, [2, 3], [2, 3, 7], 5, [2, 3, 7], 1, 6, 4, 9] 



In [56]:
board2 = [[1, 5, 6, 2, [3, 7], 9, [7], 8, 4], [[3, 7, 9], 4, [2, 3, 7, 9], [1, 3, 7, 8], [1, 3, 5, 7], 6, [1, 2, 5, 7, 9], 8, 8], [[7, 9], 8, [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 7, 9], 6, 3], [[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 3, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6], [6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 3, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 7, 9], [2, 3, 9], 5], [2, [3, 9], 8, [3, 4, 7, 9], 6, [3, 4, 5, 7], [3, 4, 7, 9], 1, [7]], [4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]], [[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 3, 9], 4, [1, 2, 3, 5], 7, 8], [8, [2, 3], [2, 3, 7], 5, [2, 3, 7], 1, 6, 4, 9]]

for i in board2:
    print(i,"\n")

[1, 5, 6, 2, [3, 7], 9, [7], 8, 4] 

[[3, 7, 9], 4, [2, 3, 7, 9], [1, 3, 7, 8], [1, 3, 5, 7], 6, [1, 2, 5, 7, 9], 8, 8] 

[[7, 9], 8, [2, 7, 9], [1, 7, 8], 4, [5, 7, 8], [1, 2, 5, 7, 9], 6, 3] 

[[3, 5, 9], 7, [1, 3, 4, 5, 9], [1, 3, 4, 9], [1, 2, 3, 5, 9], [2, 3, 4, 5], 8, [2, 3, 9], 6] 

[6, [1, 3, 9], [1, 3, 4, 9], [1, 3, 4, 7, 8, 9], [1, 2, 3, 7, 9], [2, 3, 4, 7, 8], [2, 3, 4, 7, 9], [2, 3, 9], 5] 

[2, [3, 9], 8, [3, 4, 7, 9], 6, [3, 4, 5, 7], [3, 4, 7, 9], 1, [7]] 

[4, 6, [1, 2, 3, 5, 7, 9], [3, 7, 9], 8, [2, 3, 7], [1, 2, 3, 5], [2, 3, 5], [1, 2]] 

[[3, 5, 9], [1, 2, 3, 9], [1, 2, 3, 5, 9], 6, [2, 3, 9], 4, [1, 2, 3, 5], 7, 8] 

[8, [2, 3], [2, 3, 7], 5, [2, 3, 7], 1, 6, 4, 9] 

